- themes/default/css/base.css
> Added some top margin to the first related item

- app/plugins/travelogue/traveloguePlugin.php
* If it doesn't return true then subsequent plugins implementing hookPeriodicTask get disabled.
> PROV-1240 Travelogue plugin has to return truthy

- app/lib/ca/Utils/CLIBaseUtils.php
Color are not handled under Windows : http://d.pr/i/1l2sU
> NOJIRA : Disabling cli colors under windows

- app/lib/ca/Browse/BrowseEngine.php
http://clangers.collectiveaccess.org/jira/browse/PROV-1345
> PROV-1345 Fix Browse by AuthorityAttributeValue

- assets/ca/ca.hierbrowser.js
* don't break browsers that don't have a console
> NOJIRA - Remove stray console.log() in hierarchy browser

- app/conf/media_display.conf
- app/conf/media_processing.conf
- app/lib/core/Plugins/Media/Audio.php
I'm submitting changes I've made to my local Providence install to support FLAC audio files. Hopefully these changes will be considered for inclusion in the next release.
> Proposed changes to support FLAC audio files

- app/lib/ca/BaseEditorController.php
- app/lib/ca/Browse/BrowseEngine.php
Bug solving in source id restrictions for browsing and accessing object through URL
> Bug solving in source id restrictions for browsing and accessing object through URL

- app/conf/access_restrictions.conf
- app/conf/app.conf
- app/conf/navigation.conf
- app/conf/user_actions.conf
- app/controllers/logs/ChangeController.php
- app/helpers/utilityHelpers.php
- app/lib/core/ApplicationChangeLog.php
- themes/default/views/logs/change_log_html.php
There are two different permissions: `can_view_own_change_logs` lets a user view their own changes under Manage > Logs > Change Log, while `can_view_change_logs` allows for a global view over all changes.
> PROV-1727 Add global view for change log

- app/helpers/importHelpers.php
`ExpressionParser` no longer has the `hadError()` method. Additionally catch and log errors in the import log.
> NOJIRA Fix expression parser evaluation when running import scripts

- app/lib/core/Parsers/ExpressionParser/ExpressionVisitor.php
- tests/lib/core/Parsers/ExpressionParserTest.php
We needed this and have added it. If this gets merged I'll document in the Wiki.
> NOJIRA Add trim and join support to expression parser

- app/widgets/searchBySet/views/main_html.php
* The search widget provided a link to search by set id, but this does not give any results
* Searching by set code makes the search successful again
> NOJIRA Fix Search by sets widget

- app/lib/ca/Utils/CLIUtils.php
- app/models/ca_data_importers.php
Same PR as https://github.com/collectiveaccess/providence/pull/281, but to `develop` branch
> Prov 1962: make non valid json in option a fatal error for mapping import + fix: no warnings while importing mapping from console

- app/helpers/printHelpers.php
- app/lib/core/Search/SearchIndexer.php
- app/widgets/recentComments/views/main_html.php
- themes/default/views/manage/Results/ca_item_comments_paging_controls_html.php
- themes/default/views/manage/Results/ca_item_tags_paging_controls_html.php
> Wrap a few messages in _t()

- themes/default/views/manage/user_sort_list_html.php
Change made against develop, primarily meant as a 1.7-fix.
> More _t() for UI messages

- app/lib/ca/BatchProcessor.php
- themes/default/views/bundles/hierarchy_navigation.php
Note: develop seems to be missing a couple of bugfixes to 1.7.x that have gone to master only.
> More tiny i18n fixes

- .editorconfig
https://gitter.im/collectiveaccess/support?at=59f3898032e080696e334769
> NOJIRA add .editorconfig to encourage consistency in whitespace.

- app/widgets/count/views/main_html.php
Makes a real difference in the german localization, where the words need a little more characters...
> Prettify "counts"-display by adding a non-breaking space.

- app/version.php
- install/inc/schema_mysql.sql
- support/sql/migrations/152.sql
* `ca_item_comments` already has correct datatype.
> NOJIRA Support IPv6 in all `ip_addr` columns.

- support/bin/caTools
- support/bin/caUtils
If there are no errors logged then exits with code 0 otherwise exits with code 1. Also exits with code 1 if called without any subcommand.
> NOJIRA Add exit codes to CLI tools.

- install/profiles/xml/profile.xsd
* the configuration exporter now exports the description.
> Add description to list item labels.

- app/helpers/importHelpers.php
> Fix a typo

- app/controllers/DashboardController.php
- app/lib/DashboardManager.php
- themes/default/views/dashboard/dashboard_html.php
Add a "Default" Button to the Dashboard Layout editor
> Add "Default Dashboard" Button

- Vagrantfile.debian-stretch64
This is a Vagrantfile for specific debian stretch (9.9.1, last oldstable) distribution. The Vagrantfile in master-fix brach is very old (2015) and didn't work well in debian.
> Vagrantfile for debian stretch (9.9.1).

- app/lib/Utils/CLIUtils/ImportExport.php
It solves https://collectiveaccess.atlassian.net/browse/PROV-856 and https://collectiveaccess.atlassian.net/browse/PROV-2724.
> PROV-2724 Propagate dryRun to data importer

- app/lib/Import/BaseDataReader.php
I was looking for the way to set one of the field to the current import date, so you can trace it later, when the record was imported.
The creation date might be also that field, but it is an intrinsic field, I would like to add it to any date field in the profile.
I came across a patch for it, very simple ;)
> NOJIRA Add a special source for current date.

- app/helpers/utilityHelpers.php
- app/lib/Utils/CLIUtils/Cron.php
> NOJIRA Add a new command to list tasks on the queue.

- app/lib/Plugins/Media/Mesh.php
While reviewing some code I realized there is no check for the Mesh exec file.
> NOJIRA Add missing checks for Mesh external application.

- app/lib/Plugins/Media/PDFWand.php
While reviewing some code I realized there is was no messages about detected PDF tools.
> NOJIRA Show detected external PDF applications.

- app/helpers/avHelpers.php
- app/helpers/logHelpers.php
- app/helpers/mediaPluginHelpers.php
- app/helpers/requestHelpers.php
- app/helpers/systemHelpers.php
- app/lib/Import/DataReaders/MediaInfoDataReader.php
- app/lib/Parsers/TilepicParser.php
- app/lib/Plugins/Media/Audio.php
- app/lib/Plugins/Media/Gmagick.php
- app/lib/Plugins/Media/GraphicsMagick.php
- app/lib/Plugins/Media/ImageMagick.php
- app/lib/Plugins/Media/Imagick.php
- app/lib/Plugins/Media/Mesh.php
- app/lib/Plugins/Media/Office.php
- app/lib/Plugins/Media/PDFWand.php
- app/lib/Plugins/Media/QuicktimeVR.php
- app/lib/Plugins/Media/Video.php
- app/lib/Plugins/PDFRenderer/wkhtmltopdf.php
- app/lib/Print/PDFRenderer.php
- tests/helpers/SystemHelpersTest.php
Add logging to allow tracing execution of external commands.
Closes #375
> Add logging to `exec` calls

- app/helpers/utilityHelpers.php
- app/lib/BaseModel.php
- app/lib/ConfigurationCheck.php
Additionally refactor code and move formatting function to utility helpers.
> Show max upload limit on every file upload.

- app/helpers/displayHelpers.php
- app/lib/Plugins/TaskQueueHandlers/mediaproc.php
- app/lib/TaskQueue.php
- app/widgets/trackProcessing/trackProcessingWidget.php
- app/widgets/trackProcessing/views/main_html.php
- tests/helpers/DisplayHelpersTest.php
- themes/default/css/base.css
- themes/default/css/wide.css
I would like to improve the information and look and feel of the trackProcessing widget:
* Refactored common template code into functions or helpers.
* Show links in link style.
* Show last update, it was covered by the process listing tabs.
* Add a link to Event Log in case of an error.
* Format file size using existing display helper.
> Improve track widget available information

- app/lib/Plugins/InformationService/AAT.php
- app/lib/Plugins/InformationService/BaseGettyLODServicePlugin.php
- tests/conf/linked_data.conf
While running unit test, AAT test broke due to a connection timeout. It was hardcoded to 2 seconds, but the endpoint sometimes took more than 5 seconds.
I added some code to allow configuration of curl options. I think the code can be moved to a helper, so other Information Services will reuse it, but this is the first step.
Configuration files for server and testing are also updated.
> NOJIRA Add configuration to allow setting curl connection timeout.

- app/models/ca_editor_ui_screens.php
- app/models/ca_editor_uis.php
- tests/phpunit.xml
> ISSUE #401 Update editor_ui screens cache on screen delete.

- app/lib/Parsers/TimeExpressionParser/pt_PT.lang
Changed Time Expression Parser for locale pt_PT
> Changed Time Expression Parser for locale pt_PT

- Vagrantfile
Make explicit install of PHP Redis.
> Install PHP Redis on Vagrant machine.

- app/lib/Utils/CLIProgressBar.php
Use a more compact representation of the progress ETC and ellapsed times.
> Compact time progress format.

- app/helpers/mediaPluginHelpers.php
Fix an undefined variable on refactored code.
> FIX undefined variable in refactored code

- app/helpers/mediaPluginHelpers.php
Generate correct path for dependencies.
> PR-433 Fix it again

- app/helpers/importHelpers.php
Fix regression in importHelpers by passing value converted to array.
> PROV-2868 Pass converted array

- assets/ca/ca.hierbrowser.js
UI improvement that makes the vertical hierarchy browser less confounding to use.
> PROV-2891 Make list non-clickable while loading

- app/lib/LabelableBaseModelWithAttributes.php
- app/models/ca_metadata_elements.php
Fixes display issue in metadata elements editor web user interface.
> PROV-2898 Use correct value for display

- app/lib/Configuration.php
Needed for CtCO external exports.
> PROV-2895 Implement app-name specific local config

- app/lib/Plugins/Media/PDFWand.php
- app/lib/RepresentableBaseModel.php
Adds EXIFTool-based metadata extraction for PDFs.
> PROV-2901 Extract metadata for PDFs; remove extra metadata extraction

- tests/conf/datetime.conf
Add omitted test datetime.conf file, which resolves test failures.
> PROV-2899 Adjust test config

- app/helpers/utilityHelpers.php
- app/lib/Plugins/PDFRenderer/wkhtmltopdf.php
• Now use application tmp directory
• Pass options to allow use of local files
> NOJIRA compatibility changes for wkhtmltopdf 0.12.6

- app/helpers/displayHelpers.php
- app/helpers/navigationHelpers.php
- app/lib/BaseEditorController.php
- assets/ca/ca.bundleupdate.js
• Process all ids from ca_objects relationship bundle rather than only processing id's loaded for view
• Formatting fixes
• Fix broken bundle reload JS (used by "return to home location" and other features.
> PROV-2793 Various fixes for "return to home location" feature

- themes/default/css/base.css
CSS adjustments for return to home location control.
> PROV-2793 formatting changes

- app/lib/Utils/DataMigrationUtils.php
Fixed mistake where the "log" option was not being pulled from the options array.
> NOJIRA Accept log option as defined in function documentation

- app/lib/Browse/BrowseEngine.php
PROV-2924 Fix browse facet assessment issues:
• Facets are incorrectly constrained with the multiple option is set
• Facets with no content may be shown when suppress values is configured
> PROV-2924 Fix browse facet assessment issues

- app/lib/BundlableLabelableBaseModelWithAttributes.php
- themes/default/views/bundles/ca_object_representations.php
- themes/default/views/bundles/ca_object_representations_classic.php
Resolve various issues around saving object representation-level metadata from the bundle.
>  PROV-2929, PROV-2925 Fix field saving issues with revised ca_object_representations bundle

- app/helpers/preload.php
Restore call to helper on load.
> NOJIRA restore setting of system guid constant

- app/lib/BaseModelWithAttributes.php
More fixes around saving blanks vs. null values.
> PROV-2915 improve null handling

- app/lib/Utils/CLIUtils/Cron.php
- app/lib/Utils/CLIUtils/Maintenance.php
PR removes additional redundant "quiet" option declarations.
> NOJIRA remove additional redundant quiet opt declarations

- app/lib/Plugins/SearchEngine/ElasticSearch.php
- app/lib/Plugins/SearchEngine/ElasticSearch/Query.php
> NOJIRA fix warnings resulting from sizeof being executed on null values.

- app/lib/Service/ReplicationService.php
- app/lib/Sync/Replicator.php
- app/models/ca_guids.php
PR resolves issue where some pushed media is not imported, reduces overall memory requirements and prevents memory exhaustion and improves access checking on replicated records and dependencies.
> PROV-2866 Improve data replication system

- app/helpers/guidHelpers.php
- index.php
PR ensures initialization and setting of system constant for system GUID after validation of schema takes place, preventing errors.
> NOJIRA initialize system guid

- css/main.scss
> PROV-2912 Add css

- themes/default/css/base.css
- themes/default/views/bundles/ca_item_tags.php
- themes/default/views/manage/Results/ca_item_tags_paging_controls_html.php
PR fixes two issues with user-generated content tags:
1. Rework id values for tags editor bundle for compatibility with recently changed editor naming conventions. Currently the tags editor bundle will not respond to open/close actions
2. Fix fatal error when viewing tag search results in the user generated content management interface.
> NOJIRA Fix item tag issues

- app/controllers/manage/CommentsController.php
- app/lib/BaseModel.php
- app/lib/Plugins/SearchEngine/SqlSearch.php
- themes/default/views/manage/Results/ca_item_comments_list_html.php
- themes/default/views/manage/Results/ca_item_comments_no_results_html.php
- themes/default/views/manage/Results/ca_item_tags_no_results_html.php
PR resolve various flow, error handling and functional issues with user generated content management interface, including:
• Fix non-functional delete and approve buttons
• Fix form flow to display results after action is applied
• Fix issue where some error conditions would result in a fatal error
• Fix issue where searches with no results would return a fatal error
> PROV-2946, PROV-2947 Fix various user generated content management UI issues

- tests/testsWithData/get/AttributeGetTest.php
> Update expected description for wikipedia test.

- app/lib/BundlableLabelableBaseModelWithAttributes.php
- tests/testsWithData/get/ObjectsXLocationsTest.php
PR prevents warning when attempting to apply "showCurrentOnly" option
> NOJIRA prevent warning

- themes/default/css/base.css
- themes/default/views/editor/object_representations/ajax_representation_annotation_editor_html.php
- themes/default/views/editor/object_representations/ajax_representation_image_center_editor_html.php
- themes/default/views/mediaViewers/viewerWrapper.php
PR adds text labels to "close" buttons in the bottom tool bar of media overlays.
> TD-54 Add label text to media overlay "close" icon

- app/lib/Plugins/InformationService/ALANSL.php
* Update to recent Guzzle
* Use newer Embed service
> NOJIRA Fix ALA NSL information service.

- js/mediauploader.js
Misc cleanup on media uploader component.
> PROV-2912 Cleanup

- app/lib/Browse/BrowseEngine.php
PR adds new "inHomeLocation" facet type, allowing retrieval of objects in (or not in) their home location.
> TD-72 Ad 'inHomeLocation' facet to browse engine

- tests/testsWithData/get/AttributeGetTest.php
A more conservative test to reduce the probability of changes on Wikipedia content.
> Fix broken wikipedia test

- app/lib/Attributes/Values/LCSHAttributeValue.php
PR added ability to accept LCSH bare urls in the form http://id.loc.gov/authorities/names/n88679651
> NOJIRA add ability to accept direct LCSH urls

- app/lib/IDNumbering/MultipartIDNumber.php
- app/lib/Plugins/SearchEngine/SqlSearch.php
PR addresses issue where elements of a multipart identifier may be omitted when they are repetitive due to unnecessary de-duplication.
> PROV-2983 Return full identifier

- app/lib/Plugins/SearchEngine/SqlSearch.php
PR addresses issue where qualified query on numeric field may result in SQL errors.
> PROV-2982 Avoid SQL error when querying on numeric fields

- app/helpers/importHelpers.php
PR changes media matching behavior for representation splitters to tolerate null media prefix values
> PROV-2985 Alter matching behavior to use default media prefix and to fall back to simple matching

- app/conf/datamodel.conf
- app/version.php
- install/inc/schema_mysql.sql
- support/sql/migrations/164.sql
PR adds index suggested by PR-561, and merges that migration with a pending migration adding table support for upcoming media uploader UI.
> PR-561 Add index and task queue; merge in pending schema changs from media uploader UI

- app/lib/Plugins/InformationService/VIAF.php
Reverts collectiveaccess/providence#489
> Revert "change guzzle query request array"

- app/conf/user_pref_defs.conf
- app/lib/BaseFindController.php
PR implements old PR-341 suggestion in current codebase with addition of user preference to control set listing behavior.
> PR-341 Add public sets to list subject to user preference

- install/profiles/xml/base.xml
PR fixes misspelling in base profile.
> PROV-2993 Remove an extra "r"

- app/lib/Browse/BrowseEngine.php
PR adds Pawtucket modification to address facet incorrect facet visibility when multiple facets are added and removed.
> PAWX-188 Add Pawtucket changes to address facet visibility issues when MULTIPLE facets are present.

- app/conf/annotation_types.conf
- app/lib/Auth/Adapters/Shibboleth.php
- app/lib/BaseObject.php
- app/lib/Controller/AppController.php
- app/models/ca_data_importers.php
- app/models/ca_users.php
PR resolves two core library issues:
- Prevent infinite loop and memory exhaustion when attempting to load system controller without a valid action. 
- Properly throw exception during certain single-sign-on auth errors. Previous handling would result in a fatal error while throwing the auth error – very confusing...
> PROV-3004, PROV-3005 Library fixes

- app/controllers/editor/tour_stops/TourStopEditorController.php
PR updates tour editor controller to work with current framework libraries.
> NOJIRA update old tour editor code to work with current libraries

- app/lib/HistoryTrackingCurrentValueTrait.php
PR extends dateMode=dateless support to include storage locations.
> NOJIRA add "dateless" support to storage locations

- app/controllers/lookup/IntrinsicController.php
- app/lib/BundlableLabelableBaseModelWithAttributes.php
- app/models/ca_objects.php
- app/version.php
- install/inc/schema_mysql.sql
- support/sql/migrations/165.sql
- themes/default/views/bundles/ca_objects_deaccession.php
PR Makes various enhancements for the object deaccession bundle:
- terminololgy improvements 
- add "authorized by" field with auto-suggest
- remove times from date bundles (not generally desirable for deaccession logging)
> PROV-3016 enhance deaccession bundle

- app/conf/app.conf
- app/helpers/displayHelpers.php
- app/lib/BaseFindController.php
- app/lib/Search/SearchResult.php
- app/models/ca_metadata_elements.php
- themes/default/views/find/Search/search_tools_html.php
PR implements "download all" and "downloaded selected" functionality for media in FT_MEDIA metadata attributes on selected or all records in a search/browse result set.
> PROV-2973 Implement download all functionality for media metadata elements

- app/lib/Media/BaseMediaViewer.php
- app/lib/Media/MediaViewers/pdfjs.php
- themes/default/views/mediaViewers/pdfjs.php
PR generalized pdf.js support to allow viewing of media in "media" metadata elements and site page media
> PROV-2931 Generalize pdf.js support to view attribute and site page media

- app/models/ca_sets.php
PR removes unnecessary call to caDetailLink()
> NOJIRA Remove un-needed link call

- app/controllers/find/RelatedListController.php
- app/lib/Plugins/InformationService/CollectiveAccess.php
- themes/default/views/bundles/related_list.php
- themes/default/views/find/Results/related_list_paging_controls_html.php
- themes/default/views/find/Search/related_list_html.php
PR sets unique results id's to enable paging of multiple related list bundles on the same screen.
> PROV-3033 Fix paging when multiple bundles are on the same screen

- app/lib/Service/OAIPMHService.php
PR addresses issue where he "from" option is not honored for some OAI-PMH invocations. Also adds setSpecs to record headers, as required by EBSCO.
> PROV-3037 "from" support broken for some OAI-PMH provider invocations

- app/lib/Attributes/Values/GeocodeAttributeValue.php
- app/lib/Plugins/GeographicMap/Leaflet.php
PR adds geocode attribute type option to drop a pin at the center location of a geocoded address.
> PROV-3730 Add option to "auto pin" searched locations

- app/lib/Plugins/SearchEngine/ElasticSearch/Mapping.php
- app/lib/Plugins/SearchEngine/SqlSearch.php
> NOJIRA fix regression in SqlSearch

- app/lib/BaseModel.php
PR addresses issue where width settings in UI placements are not honored for intrinsic fields.
> PROV-3041 Honor setting

- app/models/ca_lists.php
PR sets default value for list when current value is in omit config.
> PROV-3027 Set default when current value is in omit list

- app/lib/Plugins/InformationService/EOL.php
PR updates EOL.org url check to work with current API.
> NOJIRA update EOL url format check

- app/helpers/displayHelpers.php
- app/lib/BaseLookupController.php
- app/lib/BaseModel.php
- themes/default/views/bundles/ca_collections.php
- themes/default/views/bundles/ca_entities.php
- themes/default/views/bundles/ca_list_items.php
- themes/default/views/bundles/ca_loans.php
- themes/default/views/bundles/ca_movements.php
- themes/default/views/bundles/ca_object_lots.php
- themes/default/views/bundles/ca_objects.php
- themes/default/views/bundles/ca_occurrences.php
- themes/default/views/bundles/ca_places.php
- themes/default/views/bundles/ca_storage_locations.php
- themes/default/views/bundles/ca_tour_stops.php
PR prevents linking of record to itself.
> PROV-3034 Prevent linking of record to itself

- app/lib/Search/SearchIndexer.php
PR addresses issues raised in PR-661
> PR-661 Fix undefined references in search indexer

- app/lib/Parsers/ZipFile.php
- app/lib/Plugins/Media/Gmagick.php
PR addresses issue where temporary files may be left after processing. Over time these files can build up, exhausting available disk space.
> PROV-3044 Clean up files

- app/lib/Service/SimpleService.php
PR adds option to load simple service detail calls using a guid instead of row_id.
> NOJIRA add ability to load record based upon guid

- app/lib/LabelableBaseModelWithAttributes.php
PR reverses recent regression that would prevent creation of non-preferred labels.
> NOJIRA fix recent regression preventing creation of nonpreferred labels

- app/lib/BaseInterstitialController.php
- themes/default/views/editor/interstitial/interstitial_html.php
PR adds support for saving of media and file uploads initiated using a media or file metadata element. Previously, the form elements would render and be usable, but any uploaded filed were discarded at save
> PROV-3046 Allow media and file metadata elements to save when used in an interstitial form.

- app/lib/Plugins/SearchEngine/ElasticSearch.php
> NOJIRA Fix typo in ElasticSearch

- assets/ca/ca.displaytemplateparser.js
- themes/default/css/base.css
PR fixes regression where unprocessed dependent value template tags are left intact rather than being removed from final output
> NOJIRA remove unprocessed dependent value tags

- themes/default/css/base.css
PR adds styles for revised duplicate label error message.
> NOJIRA add styles for dupe label errors

- app/lib/BaseFindEngine.php
PR makes sort direction parameter case-insensitive.
> NOJIRA make sort direction ASC and DESC values case-insensitive.

- app/models/ca_item_comments.php
- themes/default/views/manage/comment_list_html.php
PR improves formatting of comment submissions in a limited way, and adds indication of source of comment.
> NOJIRA Improve formatting of comment submissions

- app/lib/Search/SearchIndexer.php
PR changes search indexer to include full idno value indexed as text in index, in addition to any specialized idno indexing. Previously, when idno-specific indexing was configured, only that indexing was performed, skipping standard text indexing.
> NOJIRA Include full idno value indexed as text in search index

- app/lib/Media/BaseMediaViewer.php
PR addresses issue where PDF url is not passed to pdfjs viewer for single page PDFs.
> PROV-2931 Ensure url is passed to pdfjs for single page PDFs

- app/lib/ConfigurationExporter.php
Further to https://github.com/collectiveaccess/providence/pull/682
> NOJIRA include restrictToTypes for child elements as well.

- app/helpers/mediaPluginHelpers.php
PR changes caching of media app paths from return values to actual paths, otherwise media processing will be broken.
> NOJIRA cache paths, not return values :-(

- app/helpers/navigationHelpers.php
- assets/jquery/jquery-tileviewer/jquery.tileviewer.js
PR updates various icon definitions to use new FA 5 styles.
> PR-653 More FontAwesome 5 migration fixes

- app/helpers/navigationHelpers.php
PR fixes set home location icon style.
> PR-653 One more

- app/helpers/navigationHelpers.php
PR updates for icon styles for FA-5 compatibility
> PR-653 Fix more icons

- app/helpers/navigationHelpers.php
PR updates for icon styles for FA-5 compatibility
> PR-653 Do another run through the icon list

- themes/default/css/base.css
PR adjusts formatting of checklists to avoid undesirable line breaks and provide more flexible spacing.
> PROV-3054 adjust grid to not break text onto multiple lines

- themes/default/css/base.css
- themes/default/views/find/SearchBuilder/ca_objects_search_builder_html.php
PR makes minor adjustment to checklist spacing
> PROV-3054 Adjust spacing

- app/lib/Plugins/Media/Mesh.php
- app/models/ca_media_upload_sessions.php
- tests/helpers/ExpressionHelpersTest.php
PR addresses bug in OBJ file parser causing all OBJ-format files to be rejected.
> PROV-3055 Parse first 100 lines of OBJ file, please.

- app/lib/Plugins/Media/Office.php
PR catches exceptions generated by PHPSpreadsheet, et al.
> PROV-2859 Catch exceptions

- app/controllers/find/QuickSearchController.php
- app/controllers/find/SearchObjectsBuilderController.php
PR fixes error introduced by expansion of deaccession and home location functionality.
> NOJIRA fix typo

- themes/default/views/bundles/ca_collections.php
AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /home/apps/collectiveaccess/providence/themes/default/views/bundles/ca_collections.php on line 77', referer: https://testcadr.jewishmuseum.cz/index.php/find/BrowseObjects/addCriteria/facet/term_facet/id/2114
> repair syntax

- install/inc/schema_mysql.sql
PR fixes installer error introduced by expansion of deaccession and home location functionality.
> PROV-3050, PROV-3051, PROV-3052 Adjust schema to load with new dependencies

- themes/default/views/bundles/ca_sets.php
PR update function calling signature for ca_sets relationship bundle.
> PROV-3057 Update calling sig

- app/lib/Parsers/DisplayTemplateParser.php
- app/lib/Parsers/TimeExpressionParser.php
- app/lib/Search/SearchIndexer.php
- tests/lib/Parsers/TimeExpressionParserTest.php
PR fixes test failures with current develop branch:
1. Display template fails to return expected values due to incorrect handling of "length" option when processing data in container
2. INDEX_ANCESTORS search indexing option generates incorrect indexing entries preventing expected hierarchical expansion of search results
3. Incorrect processing of date ranges as described in https://collectiveaccess.org/support/index.php?p=/discussion/300669/date-format-1947-06-1947-june-31st#latest
> Fix test failures in develop branch

- app/conf/visualization.conf
> Bug in configuration

- app/conf/visualization.conf
PR adds missing } to visualizations.conf
> NOJIRA fix config error

- app/lib/Plugins/PDFRenderer/domPDF.php
- app/lib/Search/SearchResult.php
PR fixes issue where incorrect array handling would cause warnings to be emitted; added configurability for dompdf chroot.
> NOJIRA catch and prevent array warning; make dompdf chroot configurable.

- app/conf/search.conf
I hope, this is last related change.    
By having corret conf, it will be easier to admins to configure it.
> idno regexes format

- app/conf/search.conf
PR corrects search.conf configuration to use associative list.
> Use correct configuration

- themes/default/views/bundles/ca_object_representations.php
- themes/default/views/bundles/ca_object_representations_classic.php
PR adds support for revised sorting controls to representation bundles.
> PROV-3057 Update representation bundles to use revised sorting controls

- app/helpers/importHelpers.php
PR adds skipIfAllEmpty and skipIfAnyEmpty options to importer for relationship blocks in refineries.
> NOJIRA add skipIfAllEmpty and skipIfAnyEmpty options

- app/conf/search_indexing.conf
PR fixes typo in comment on search_indexing.conf and adds hierarchical indexing for storage locations
> NOJIRA Fix search_indexing.conf issues

- app/lib/Utils/CLIUtils/ImportExport.php
PR adds existing addAllDatasets importer option to CLI caUtils-based importer interface.
> NOJIRA expose addAllDatasets option in CLI importer

- app/lib/ExternalExportManager.php
- app/lib/Plugins/ExternalExport/BaseExternalExportTransportPlugin.php
- app/lib/Plugins/ExternalExport/Transport/sFTP.php
PR adds code to cleanup temporary data files created by external export framework when transporting files via SFTP.
> PROV-2892 Cleanup export tmp files

- app/lib/Browse/BrowseEngine.php
PR added ability to specify text value for attribute criteria facet specs; useful for creating "stable" browse urls.
> NOJIRA add capability to use text values for attribute facets

- app/lib/Media/BaseMediaViewer.php
- themes/default/views/mediaViewers/pdfjs.php
PR resolves two issues in original PR for this feature:
- Will now fall back to "original" media if compressed version does not exist
- Uses correct field name for attribute media
> PROV-3066 Fall back to original media if compressed does not exist

- app/helpers/utilityHelpers.php
- app/lib/BaseFindEngine.php
- app/lib/Search/SearchIndexer.php
- support/sql/migrations/167.sql
- themes/default/views/pageFormat/pageFooter.php
PR adds required database migrations, fix in new sorting code for mysql8 and OpCache performance display.
> Add missing migration; fix mysql 8 compatibility issue; add cache perf stats

- app/lib/Browse/BrowseEngine.php
PR resolves SQL error when attempting to use a label facet in an object representation browse.
> PROV-3071 Fix SQL error in label facet browse for object representations

- app/helpers/utilityHelpers.php
PR rounds currency values to two decimal places.
> NOJIRA ensure imported currency values use only two decimal places

- app/conf/media_display.conf
- app/helpers/displayHelpers.php
- app/helpers/themeHelpers.php
- app/helpers/utilityHelpers.php
- app/lib/Media/MediaViewers/MediaElement.php
- app/lib/RepresentableBaseModel.php
PR adds option to include an image representation above the player for an audio representation. The primary, or first-found image will be used.
> Add ability to display image representations in audio player

- app/lib/Browse/BrowseEngine.php
PR resolves issue preventing accurate browse results for facets on information service values.
> NOJIRA Fix broken browse on information service values

- themes/default/css/sets.css
- themes/default/views/manage/set_list_by_user_html.php
Add a class to the td for the User header of the Set list by user listing, and minimally decorate it to help with the understanding of list.
> Set list by user: highlight user headings to help read the listing

- app/helpers/utilityHelpers.php
{} no longer supported in php8
> use [] instead of {}

- app/lib/Parsers/TimeExpressionParser/cs_CZ.lang
The same file, but in master branch.
> Time parser cs

- themes/default/css/base.css
PR changes summary formatting to align headings and text to top of table row.
> NOJIRA align summary headings to top

- app/conf/app.conf
PR localizes "required" flag in field label areas in editor interface.
> PR-811 Localize "required" display flag

- app/helpers/CLIHelpers.php
I'm not sure how this would even compile, so maybe this file isn't used anymore?
> remove stray \

- app/lib/Db/mysqli.php
I'm not 100% sure this is accurate, it's possible that continue 2; is more correct.
> replace continue with break

- app/models/ca_media_upload_sessions.php
- install/inc/schema_mysql.sql
- support/sql/migrations/167.sql
PR adds fields required for Metabolic front-end UI to media upload sessions.
> PROV-3075 Add fields to migration

- app/lib/Plugins/TaskQueueHandlers/mediaproc.php
PR ensures user-selected center point is used when cropping images to center in background via task queue.
> PROV-3080 Respect center for cropping when processing in background

- support/bin/caTools
- support/bin/caUtils
> NOJIRA bump copyright dates

- themes/default/views/pageFormat/pageFooter.php
PR updates copyright date in footer to 2021
> NOJIRA bump footer year

- app/lib/Plugins/Media/Imagick.php
PR removes use of deprecated Imagick function.
> NOJIRA remove use of deprecated imagick function

- app/lib/Plugins/Media/Gmagick.php
PR resolves incorrect invocation introduced in a recent commit.
> NOJIRA Fix gmagick regression

- app/lib/Parsers/ExpressionParser.php
Perhaps Hoa has been refactored.
> Fix class name for Llk

- app/lib/Browse/BrowseEngine.php
PR adds support for restrict_to_relationship_types specifications in browse facets employing relative_to
> NOJIRA Support relationship type restrictions in browse facets using relative_to 

- app/helpers/displayHelpers.php
- app/lib/HistoryTrackingCurrentValueTrait.php
- themes/default/css/base.css
- themes/default/views/bundles/ca_collections.php
- themes/default/views/bundles/ca_object_lots.php
- themes/default/views/bundles/ca_objects.php
- themes/default/views/bundles/history_tracking_current_contents.php
- themes/default/views/bundles/set_home_location_html.php
PR improves "return to home location" options in relationship bundles and storage location "current contents" bundle by:
- Fixes fatal errors in current contents bundle
- Simplifies calling pattern (somewhat) for controls
- Improves (somewhat) the user interface
> PROV-2793 Clean up "return to home location" bundle controls

- app/lib/Service/ItemService.php
* Also allow representations to be saved when there are no relationships.
> NOJIRA Allow representations to be set during editItem handler in the item service

- app/lib/BaseModelWithAttributes.php
PR resolves issue where modification metadata alerts configured to watch child elements in containers are not triggered.
> PROV-3101 Modification metadata alerts are not getting triggered for elements inside containers.

- app/lib/BaseModel.php
- app/lib/Utils/DataMigrationUtils.php
PR adds checks for setting of fields which are not present in all cases, preventing spurious errors from being displayed
> PROV-3099 Add checks for setting of fields which are not present in all cases

- app/lib/BundlableLabelableBaseModelWithAttributes.php
- app/lib/IDNumbering/MultipartIDNumber.php
The multipart id numbering system supports two modes of sequence number generation via SERIAL elements: (1) a single sequence for the entire table (eg. all objects regardless of type) or (2) separate per-type sequences 
This PR adds a third option, allowing specification of sequences that are shared across several selected types. This allows a single sequence to be used for groups of related types (Eg. different types of photographic materials in a photo collection).
> PROV-3103 Allow multiple types to share idno SERIAL sequences

- app/conf/media_processing.conf
- app/helpers/avHelpers.php
- app/lib/Plugins/Media/Video.php
PR adds support for MTS format video (see https://en.wikipedia.org/wiki/.m2ts)
> PROV-3107 Add support for MTS video

- app/lib/ModelSettings.php
- app/lib/RepresentableBaseModel.php
PR fixes warning when no settings are available for a list item and corrects a typo in a comment
> NOJIRA Misc fixes

- app/locale/messages.pot
> Updated strings

- app/conf/media_display.conf
PR adds MPT mimetype to video viewer, allowing videos in that format to be viewed using the standard player.
> PROV-3107 Use video viewer

- app/lib/BaseModel.php
PR adds more checks for unreadable media.
> PROV-3110 Catch unreadable media

- app/lib/Plugins/Media/Video.php
PR resolves issue where previews are not created for very short videos
> PROV-3111 Force start time for preview to zero when length of video is shorter than offset

- app/helpers/navigationHelpers.php
PR rewrites display link urls generated in service context to use interactive entry point rather than service.php.
> NOJIRA rewrite display link urls generated in service context 

- app/lib/IDNumbering/MultipartIDNumber.php
PR resolves issue causing incorrectly formed SQL statement when generating SERIAL idno.
> PROV-3114 Avoid SQL error when using type-restricted policies for id numbering

- app/lib/Service/IIIFService.php
PR removes dependency on existence of "original" multifile media version in IIIF service. It will now fall back to preview versions if required.
> NOJIRA remove dependence on "original" media version in IIIF image service

- app/lib/Plugins/Media/Imagick.php
With current version of Imagick and ImageMagick, when EXIF orientation tags are set distorted derivative preview images may result. PR implements working rotation.
> PROV-3119 Fix broken handling of EXIF-rotated images in Imagick/Imagemagick media processing back-end

- install/inc/schema_mysql.sql
PR resolves various errors in the database schema. These errors are ignored by most versions/configurations of MySQL for some reason, but should be resolved nonetheless.
> NOJIRA Fix various errors and inconsistencies in the database schema

- app/models/ca_metadata_alert_rules_x_user_groups.php
- app/models/ca_metadata_alert_rules_x_users.php
PR fixes incorrect text labels on access drop-downs for metadata alerts
> NOJIRA Fix label text

- app/lib/BaseModel.php
PR ensures proper quoting of table.field sort parameters in find()
> PROV-2788 Ensure proper quoting

- app/lib/ConfigurationExporter.php
PR filters deleted lists from exported profiles. See https://collectiveaccess.org/support/index.php?p=/discussion/300744/help-needed-importing-vocabulary-list-items#latest
> PROV-3127 Filter deleted lists from exported profiles

- app/lib/Plugins/Media/Gmagick.php
PR modifies GMagick behavior when EXIF orientation tag is set to avoid distorted previews.
> PROV-3119 Changes to resolve distorted previews

- app/lib/BaseSearchController.php
PR fixes regression preventing viewing of last page of search results.
> PROV-3130 Restore ability to reach last page using mathematics

- app/lib/BaseModelWithAttributes.php
- app/lib/Browse/BrowseEngine.php
- app/lib/BundlableLabelableBaseModelWithAttributes.php
- app/lib/LabelableBaseModelWithAttributes.php
- app/lib/ModelSettings.php
- app/lib/Search/SearchIndexer.php
- app/lib/Search/SearchResult.php
- app/models/ca_editor_uis.php
- app/models/ca_metadata_elements.php
- app/models/ca_users.php
- app/models/ca_watch_list.php
PR merges in changes from users addressing various warnings and minor issues.
> Changes to address various warnings and reported issues

- assets/pdfjs/viewer/viewer.js
- themes/default/views/mediaViewers/pdfjs.php
PR loads PDF.js localization files; modifies auto-highlighting of search terms to ensure full phrase searching.
> Resolves #957 - Load localization files

- install/profiles/xml/profile.xsd
PR adds missing ObjectLots and FloorPlan types to validation schema.
> Resolves #975 Add missing types

- assets/ca/ca.querytranslator.js
- themes/default/views/find/SearchBuilder/search_controls_html.php
PR improves handling of errors and strings with quotes. Now can recover from invalid filters (previous behavior got search builder "stuck" in unrecoverable crash loop) and handle escaping of quoted strings.
> Improve query builder error handling and character escaping

- app/helpers/printHelpers.php
- app/lib/BaseEditorController.php
* Prior to this if you were using a theme other than the default theme these components would not render.
> Make download options and debug output themeable

- app/helpers/themeHelpers.php
- app/models/ca_search_forms.php
PR addresses issue preventing container sub-elements from participating in advanced search form searches.
> Ensure that container sub-elements are searchable in adv search forms

- app/lib/LabelableBaseModelWithAttributes.php
- app/lib/Search/SearchIndexer.php
PR resolves reported indexing issues:
1. Related items are indexed as private even if access is set to public
2. Non-preferred labels on list items are not indexed against records with list metadata elements except on reindex
> Resolve indexing issues

- app/lib/BundlableLabelableBaseModelWithAttributes.php
* Enables hiding / showing / rearranging of fields through a plugin.
> Add a hook to change the html form before it gets sent out

- app/lib/HistoryTrackingCurrentValueTrait.php
* History tracking policy uses type idno but form uses type_id
* Supports pulling request parameter based on type_id and type idno
> Enable setting of attribute values on interstitial

- app/lib/ConfigurationCheck.php
> Check the media upload tmp dir is writable

- app/lib/Attributes/Values/LCSHAttributeValue.php
PR adds support for Library of Congress RBMSTR authority.
> Add support for LC RBMSTR authority

- app/lib/BaseSearchBuilderController.php
- themes/default/views/find/SearchBuilder/ca_collections_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_entities_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_loans_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_movements_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_object_lots_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_object_representations_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_objects_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_occurrences_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_places_search_builder_html.php
- themes/default/views/find/SearchBuilder/ca_storage_locations_search_builder_html.php
PR resolves issue in search builder with duplicated search buttons and inability to view final page of multipage results.
> Fix paging and form display errors

- app/helpers/browseHelpers.php
- themes/default/views/find/Browse/browse_controls_html.php
PR modifies browse to respect show_all_for_no_criteria_browse browse.conf setting.
> Resolves #1017

- app/models/ca_object_representations.php
I just did a pull from `develop` and this didn't look safe.
> Remove die statement

- assets/ca/ca.hierbrowser.js
PR addresses recently introduced typo
> Fix recently introduced typo is hierbrowser library

- app/lib/BaseModel.php
PR prevents fatal SQL error when IN operator is passed without value list.
> Catch SQL error when using IN operator with no values

- app/controllers/logs/GlobalChangeController.php
- app/lib/ApplicationChangeLog.php
PR re-establishes function of "change type" filter in global change log.
> Fix broken change type filter

- support/scripts/import_utility_functions.sh
PR adds bash utility functions for automation of command-line data imports.
> Add import scripting utils

- themes/default/views/find/SearchBuilder/ca_places_search_builder_html.php
* Copied from ca_objects_search_builder_html.php
> Fix syntax error for the places search builder

- app/controllers/administrate/setup/ElementsController.php
- app/models/ca_metadata_elements.php
- install/inc/Installer.php
PR improves poor performance when adding or editing metadata element configuration in the web UI, or installing a profile.
> Improve poor performance on insert or update of metadata element rows

- app/conf/media_display.conf
- app/lib/BaseModel.php
- app/lib/Media.php
- app/lib/Plugins/Media/Mesh.php
PR updates sizing for 3d viewer and improves OBJ parsing.
> Update 3d viewer

- app/models/ca_data_exporters.php
PR adds caching and reduces method calls in loops to improve (somewhat) exporter performance. Fix broken "repeatmappings" option.
> Improve exporter performance and fix broken repeatingmappings option

- app/lib/HistoryTrackingCurrentValueTrait.php
- app/lib/Plugins/SearchEngine/SqlSearch2.php
PR resolves issues with future location dates not transitioning to present dates properly; reduces memory usage in SQLSearch2 for certain types of queries.
> Improve handling of future dates in history tracking

- app/models/ca_data_exporters.php
PR fixed incorrect handling of repeatmappings setting that would result in it being ignored.
> Fix broken repeatmappings setting

- app/conf/user_pref_defs.conf
- app/controllers/manage/MetadataExportController.php
- app/helpers/displayHelpers.php
- app/lib/Export/ExportFormats/ExportXML.php
- app/models/ca_data_exporters.php
PR improves exporter with the following changes:
1. Add user preference to control whether exports from editor are immediately downloaded or go to a landing page.
2. Make last used exporter default in editor exporter list.
3. Add additional logging.
> Exporter improvements

- app/conf/search.conf
- app/lib/BaseModel.php
- app/lib/LabelableBaseModelWithAttributes.php
- app/lib/Search/SearchResult.php
- composer.json
- tests/lib/AttributeValues/GeocodeAttributeValueTest.php
- tests/lib/AttributeValues/TGNInformationServiceAttributeValueTest.php
- tests/lib/IDNumbering/MultipartIDNumber.php
- tests/lib/Models/ModelSettingsTest.php
- tests/lib/Parsers/ExpressionParserTest.php
- tests/lib/Search/ElasticSearch/MappingTest.php
- tests/models/ca_setsTest.php
- tests/phpunit.xml
- tests/plugins/relationshipGenerator/RelationshipGeneratorPluginConfigurationTest.php
- tests/testsWithData/get/AttributeGetTest.php
- tests/testsWithData/get/RelatedGetTest.php
- tests/testsWithData/get/SearchResultGetTest.php
PR updates tests to run under PHPUnit 9.5 and resolves various test failures.
> Update tests to run under PHPUnit 9.5 and fix failures

- app/conf/media_display.conf
- app/lib/Media/MediaViewers/pdfjs.php
- assets/pdfjs/viewer/viewer.js
- themes/default/views/mediaViewers/pdfjs.php
PR adds options to control the scroll mode used for PDFJS on initial load.
> Make scroll mode on load configurable

- themes/default/views/find/Browse/ajax_browse_facet_html.php
PR fixes non-functional facet "apply" button when non-numeric facet values are present
> Fix non-functional facet "apply" button

- app/helpers/utilityHelpers.php
- app/lib/Attributes/Values/ListAttributeValue.php
PR modifies list attributes to attempt match on commas separated values (Eg. Saw, Chain) using serialized version (Chain Saw) if no initial match.
> Modify list attributes to attempt match on commas separated values

- app/models/ca_metadata_type_restrictions.php
- app/plugins/notifications/notificationsPlugin.php
- app/refineries/objectRepresentationSplitter/objectRepresentationSplitterRefinery.php
Hello.
I am not completely sure about change in 
app/refineries/objectRepresentationSplitter/objectRepresentationSplitterRefinery.php
so please revise more thorougly.
Václav
> Some typos/copypaste errors

- app/lib/Auth/Adapters/CaUsers.php
- app/models/ca_users.php
PR resolves issue #1083 - users with fully numeric user names cannot log in.
> Allow login with numeric username

- app/lib/BundlableLabelableBaseModelWithAttributes.php
- app/lib/HistoryTrackingCurrentValueTrait.php
- app/lib/Search/SearchResult.php
PR resolves fatal errors in new bundle-level "current value" display code.
> Resolve fatal errors in bundle-level current value display

- app/lib/Utils/DataMigrationUtils.php
- app/lib/Utils/DataMigrationUtils/en_AU.lang
- app/lib/Utils/DataMigrationUtils/en_CA.lang
- app/lib/Utils/DataMigrationUtils/en_US.lang
- tests/lib/Utils/DataMigrationUtilsTest.php
PR Improves entity name splitter with revised suffix/prefix handling, improved consistency between straight and comma delimited names, and support for recognition of surname prefixes
> Improve entity name splitter

- app/models/ca_data_exporters.php
* Support exporting of contents of relationship tables
* Tweak to column headers for CSV
* Properly default the column name if it doesn't have a display label
* Support CSV_delimiter and CSV_enclosure for column headings
> Tweaks to data exporter

- app/conf/datamodel.conf
- app/models/ca_collection_labels.php
- app/models/ca_loan_labels.php
- app/models/ca_media_upload_session_files.php
- app/models/ca_movement_labels.php
- app/models/ca_object_labels.php
- app/models/ca_object_lot_labels.php
- app/models/ca_object_representation_labels.php
- app/models/ca_occurrence_labels.php
- app/models/ca_tour_stop_labels.php
- app/version.php
- install/inc/schema_mysql.sql
- support/sql/migrations/170.sql
- support/sql/migrations/171.sql
- support/sql/migrations/172.sql
- tests/lib/Db/DbTest.php
PR merges in schema revisions from dev/perf branch (to be merged soon); modifies schema to support utfmb4 character set; add new media uploader table to schema
> Schema revisions prior to release

- app/models/ca_editor_ui_screens.php
- themes/default/views/bundles/hierarchy_location.php
- themes/default/views/bundles/hierarchy_navigation.php
* Add customisable name for counts text
* Support restrict_to_types for search / add child in hierarchy
* Fixes to undefined variables / typos
> Tweaks to hierarchy_location / hierarchy_navigation bundles

- app/lib/Plugins/Media/Gmagick.php
- app/lib/Plugins/Media/Imagick.php
PR adds "3" as valid EXIF orientation value, allowing 180 degree rotations.
> Accept orientation code 3 (180 degree rotation)

- app/conf/user_pref_defs.conf
- app/locale/messages.pot
- install/inc/Installer.php
> Few typos &  translation catalog regeneration

- app/lib/Plugins/SearchEngine/SqlSearch2.php
PR adds explicit support for set id searches in SqlSearch2 engine.
> Add explicit support for set id searches

- app/widgets/trackProcessing/conf/trackProcessing.conf
- app/widgets/trackProcessing/trackProcessingWidget.php
- app/widgets/trackProcessing/views/main_html.php
* Adds a configurable limit to trackProcessingWidget
* Formats dates using localised dates
> Don't clobber the server when there are too many jobs pending/processed

- app/helpers/utilityHelpers.php
* It's possible to add a rich text editor to preferred labels.
* I don't think any html tags within these should be included.
> Strip tags from sortable values.

- install/css/site.css
- install/inc/page2.php
- themes/default/css/error.css
- themes/default/views/system/configuration_error_html.php
- themes/default/views/system/configuration_error_install_html.php
PR updates error views with new logo and improved spacing.
> Update error page logo and improve spacing

- app/lib/BaseModel.php
- app/lib/BundlableLabelableBaseModelWithAttributes.php
- app/lib/Parsers/TilepicParser.php
- app/printTemplates/bundles/pdf.css
- app/printTemplates/results/pdf.css
- app/printTemplates/sets/pdf.css
- app/printTemplates/summary/pdf.css
PR resolves various minor issues:
- Allow subtitles on audio files
- Allow page numbering in PDF output footers
- Ensure EXIF metadata is extracted properly when processing tilepics
> Subtitle, PDF output and EXIF fixes

- themes/default/views/bundles/hierarchy_navigation.php
PR resolves recently introduced syntax error in hierarchy_navigation bundle.
> Resolve syntax error introduced in d037b3b71d7eddd63fb8b41d91c0af9efd8002a9

- install/inc/schema_mysql.sql
PR converts all "references" foreign key declarations to constraint syntax to ensure similar behavior between MySQL and MariaDB.
> Convert all "references" foreign key declarations 

- app/lib/Utils/CLIUtils.php
- app/lib/Utils/CLIUtils/Test.php
PR adds utility to test outgoing email configuration to caUtils.
> Add outgoing email test utility

- app/lib/BundlableLabelableBaseModelWithAttributes.php
* This allows plugins to attach a transaction to the instance if
necessary.
> Trigger hookBeforeBundle before adding a transaction to the instance

- app/controllers/system/AuthController.php
PR adds checks to ensure that redirect URL passed to login process is local to server, preventing redirect to arbitrary urls. Thanks to @noobpk for report.
> Validate redirect url onl login

- app/helpers/displayHelpers.php
PR removes link display than can potentially render unfiltered content. Thanks for @ranjit-git for finding this.
> Remove link display to present XSS

- app/controllers/batch/EditorController.php
- app/controllers/batch/MediaImportController.php
- app/controllers/batch/MetadataImportController.php
- themes/default/views/batch/mediaimport/import_options_html.php
- themes/default/views/batch/metadataimport/importer_run_html.php
PR adds CSRF checks to batch media, metadata and editor forms.
> Add CSRF to batch forms

- app/controllers/manage/PawtucketController.php
- app/controllers/manage/sets/SetEditorController.php
- app/helpers/displayHelpers.php
- app/helpers/navigationHelpers.php
- app/helpers/utilityHelpers.php
- app/lib/BaseEditorController.php
- themes/default/views/bundles/change_type_html.php
- themes/default/views/bundles/set_home_location_html.php
- themes/default/views/manage/Pawtucket/edit_global_values_html.php
PR adds CSRF checks to additional endpoints that previously excluded them.
> Add CSRF checks to additional endpoints

- index.php
PR add no-store header to prevent back-button use after logout.
> Add no-store header to prevent back-button after logout

- app/lib/MetadataAlerts/TriggerTypes/Base.php
- app/lib/MetadataAlerts/TriggerTypes/Submission.php
- app/lib/Utils/CLIUtils/Maintenance.php
- app/models/ca_media_upload_sessions.php
- app/models/ca_metadata_alert_triggers.php
- themes/default/views/manage/metadata_alert_rules/ajax_rule_trigger_settings_form_html.php
PR improves support for Pawtucket-submitted media/metadata imports by:
- adding submission alert type, to allow for dashboard and email alerts related to submissions 
- improvements to submission processing
> Improvements to metadata alerts and Pawtucket importer processing

- app/conf/replication.conf
- app/lib/Service/ReplicationService.php
- app/lib/Sync/Replicator.php
PR adds options to  to replication framework to control chunk size and behavior when file upload push fails.
> Add options to control chunk size and behavior to replicator 

- app/conf/assets.conf
- app/lib/Plugins/Media/Video.php
- themes/default/css/base.css
PR changes out VideoJS player for Plyr viewer (https://plyr.io)
> Use Plyr for video

- app/controllers/system/ErrorController.php
- app/helpers/errorHelpers.php
- app/helpers/utilityHelpers.php
- app/lib/BaseModel.php
- app/lib/Browse/BrowseEngine.php
- app/lib/Controller/Request/RequestHTTP.php
- app/lib/Logging/Eventlog.php
- app/models/ca_users.php
PR centralizes creation of HTMLPurifier instances, ensuring the same configuration policies are used across the application.
> HTMPurifier refactor

- app/controllers/manage/search_forms/SearchFormEditorController.php
- app/helpers/utilityHelpers.php
PR modifies search form editor to use appropriate access constant when checking accessibility, preventing warnings on some systems.
> Use appropriate constant when checking seach form access

- app/helpers/displayHelpers.php
- app/lib/BaseEditorController.php
PR updates incorrect method calls causing errors when using the return to location function.
> Fix incorrect method call

- app/lib/Plugins/Media/Audio.php
PR adds support for playback of AAC audio and ensures encoding works for files with  cover images.
> Add support for playback of AAC audio

- app/helpers/errorHelpers.php
- themes/default/views/system/auth_error_html.php
- themes/default/views/system/configuration_error_html.php
- themes/default/views/system/configuration_error_schema_update_html.php
- themes/default/views/system/fatal_error_html.php
- themes/default/views/system/forgot_password_html.php
- themes/default/views/system/logged_out_html.php
- themes/default/views/system/login_html.php
- themes/default/views/system/no_setup_html.php
- themes/default/views/system/password_reset_form_html.php
- themes/default/views/system/password_reset_instructions_html.php
- themes/default/views/system/welcome_html.php
PR modifies system error and login views to use standardized functions for getting login and theme path that are declared at the beginning of the bootstrap process. This prevents errors during exception display due to branding functions not yet being declared.
> Clean up system error and login views

- app/lib/Controller/Request/RequestHTTP.php
PR corrects double-slashed path.
> Clean up path

- app/conf/app.conf
- app/controllers/manage/sets/SetEditorController.php
- app/lib/Attributes/Attribute.php
- app/models/ca_sets.php
- themes/default/views/bundles/hierarchy_location.php
- themes/default/views/lookup/set_hierarchy_ancestors_json.php
- themes/default/views/lookup/set_hierarchy_level_json.php
PR adds support for hierarchy_location (hierarchy browser) bundle in set editor, making management of sub-sets much easier.
> Add support for hierarchy_location (hierarchy browser) bundle in set editor

- app/helpers/importHelpers.php
PR adds options to control whether file sizes are processed using megabytes (1000) or mebibytes (1024)
> Add options to control display of filesize values

- app/models/ca_data_importers.php
PR ensures that attribute source values are set for repeat values during import.
> Ensure attribute source values are set for repeat values in importer

- app/conf/external_applications.conf
- app/lib/Parsers/TilepicParser.php
- app/lib/Search/SearchIndexer.php
PR resolves errors during creation of tilepic files when the ImageMagick CLI media plugin is in use. (Reported by BruceK: https://collectiveaccess.org/support/index.php?p=/discussion/comment/324249#Comment_324249)
> Fix imagemagick tilepic errors

- app/helpers/mediaPluginHelpers.php
PR adjusts imagemagick presence test for path format. (Missed this before).
> Remove command (oops)

- app/lib/Attributes/Values/NumericAttributeValue.php
PR provides localized input and output for numeric attributes. See https://www.collectiveaccess.org/support/index.php?p=/discussion/comment/324264
> Provide localized input and output for numeric attributes.

- app/lib/Media/BaseMediaViewer.php
- app/lib/Parsers/TilepicParser.php
- themes/default/views/mediaViewers/Mirador.php
- themes/default/views/mediaViewers/MiradorManifest.php
- themes/default/views/mediaViewers/UniversalViewerManifest.php
This PR allows to download image, which is currently viewed in Mirador.
> Mirador download

- .htaccess
> Add txt to .htaccess

- app/lib/Parsers/DisplayTemplateParser.php
consistent null coalescing testing on aggregateUnique (warning on non-existance in DisplayTemplateParser)
> consistently null coalescing on aggregateUnique

- app/lib/BundlableLabelableBaseModelWithAttributes.php
ca_lists doesn't seem to have the disable_acl property so I property tested within the condition
> check if acl property exisits

- app/lib/BaseFindController.php
* Help encourage opening in correct applications on some operating systems
> Fix mime type for csv and tsv

- app/lib/Utils/CLIUtils/Maintenance.php
fix-permissions wasn't updating the permissions on the htmlpurifier library. Added extra parameter to fix this.
> Permission fix

- composer.json
https://github.com/php-http/discovery/issues/213
> NOJIRA fix composer install with new dependency

- app/lib/Auth/Adapters/Shibboleth.php
Backport https://github.com/collectiveaccess/pawtucket2/pull/67 into providence
> NOJIRA Support user creation in Shibboleth authentication adapter

- app/plugins/iDigBioExport/iDigBioExportPlugin.php
- app/plugins/pawtucketMediaImport/pawtucketMediaImportPlugin.php
* Move Periodic Task output to the CA log
* Allow plugins after pawtuckeMediaImport to also process periodic tasks
> NOJIRA don't litter stdout

- app/lib/BaseModel.php
- app/lib/Plugins/Media/Audio.php
- app/lib/Plugins/Media/BaseMediaPlugin.php
- app/lib/Plugins/Media/GD.php
- app/lib/Plugins/Media/Gmagick.php
- app/lib/Plugins/Media/GraphicsMagick.php
- app/lib/Plugins/Media/ImageMagick.php
- app/lib/Plugins/Media/Imagick.php
- app/lib/Plugins/Media/Mesh.php
- app/lib/Plugins/Media/Office.php
- app/lib/Plugins/Media/PDFWand.php
- app/lib/Plugins/Media/Video.php
- app/lib/Plugins/TaskQueueHandlers/mediaproc.php
PHP8 has removed the function each(), this has replaced where possible the while(list() = each()) loop with a foreach loop
> PHP8 compatibility each() fix

- app/lib/Utils/CLIUtils.php
Patched to fix Chenhall imports that result in flat lists with dropped values. 
This change backports the changes to the Chenhall importer from version 1.8 to the 1.7 release. Additionally, due to changes in the xlsx format, the importer logic was updated to match Chenhall's 2023 format.
> patch Chenhall importer with 1.8 backport

- app/lib/Search/SearchEngine.php
* Fix undefined variable which was preventing this from working
* Retrieve $t_table earlier in the method
> Allow configuration for quickly searching based on idno regex

- app/lib/Db/pdo_mysql.php
I experimented with pdo_mysql and found this fatal error.
> Fix fatal error in pdo_mysql

- install/profiles/xml/dacs_heritage.xml
> Corrected display format for Creator column

- install/profiles/xml/dacs_heritage.xml
> Remove "null" date type

- app/models/ca_site_pages.php
- app/version.php
- support/sql/migrations/195.sql
- themes/default/views/manage/Pawtucket/page_list_html.php
Enable the ability to sort menu items, or content pulled into other pages.
> Add rank to site pages

- app/lib/BaseQuickAddController.php
@collectiveaccess
There were an error in the order of the function calls causing an error with the Quick Add view. 
I fixed it by reordering the code as it is in CA 2.0.
> Fixed QuickAdd

- app/lib/Service/SearchJSONService.php
NOJIRA - allow to use templates to format web services search results
> NOJIRA - allow to use templates to format web services search results

- install/profiles/xml/dacs_heritage.xml
> Corrected a typo in dacs_heritage.xml

- app/helpers/gisHelpers.php
> Fix for EXIF-Problem for media where no exif data is present

- app/conf/global.conf
- app/helpers/post-setup.php
- setup.php-dist
Enable the ability to edit the port number and change SSL default to false
> DB Connect Fixes

- app/conf/app.conf
Update app.conf : logo for reports, svg is not valid for a docx export
> Update app.conf : logo for reports, svg is not valid for a docx export

- composer.json
Updated to patched version
https://www.cve.org/CVERecord?id=CVE-2024-27354
https://www.cve.org/CVERecord?id=CVE-2024-27355
> phpseclib security vunerability

- app/helpers/importHelpers.php
Maybe the original author was hedging bets. Non-zero chance that this makes it worse, please double check! Thanks
> Small UI typo around double-negative skipIfNotValue

- app/service/helpers/SchemaHelpers.php
Added the namespace to these method calls to fix issue #1706
> Resolves #1706
