install/inc/schema_mysql.sql
An index is defined two times, causing an error during setup.
=> Remove duplicate index that causes a setup error

themes/default/css/base.css
Just a minor usability improvement to help users recognize read-only fields. #F0F0F0 is default for FF and IE, slightly different from Chromes default bg color for disabled input elements (#EBEBE4).
=> Grey background for disabled input elements

themes/default/css/base.css
Just a little fix for search/browse criteria that span multiple lines.
=> Fix search/browse criteria CSS

app/conf/access_restrictions.conf, app/lib/core/Controller/Request/RequestHTTP.php, app/lib/core/Controller/Request/Session.php, app/service/controllers/AuthController.php
This finally allows us to re-use sessions for the API. While this is technically not REST it's common practice and allows us to not basic auth for every request.
The idea is that you call the /service.php/auth/login endpoint via GET (w/ basic auth) and it'll give you an authToken. Append this authToken as GET parameter to any subsequent service API calls and you'll be authenticated and find yourself in the same session.
Auth tokens don't last very long (which is kind of the point) so you'e going to have to re-authenticate every once in a while, when you get a 401.
The old "basic auth on every request" way still works for compatibility.
A good next step would be to allow users to generate API keys that can be used for service authentication instead of their account passwords.
I updated the …
=> PROV-1268 Add token-based authentication to web service API

.travis.yml, app/conf/datamodel.conf, app/lib/ca/BundlableLabelableBaseModelWithAttributes.php, app/lib/ca/LabelableBaseModelWithAttributes.php, app/lib/ca/Utils/CLIUtils.php, app/lib/core/BaseModel.php, app/lib/core/BaseModelWithAttributes.php, app/lib/core/Controller/Request/RequestHTTP.php, app/lib/core/Search/SearchIndexer.php, app/models/ca_search_indexing_queue.php, app/version.php, index.php, install/inc/Installer.php, install/inc/page2.php, install/inc/schema_mysql.sql, support/sql/migrations/120.sql, tests/lib/core/Db/DbTest.php, tests/testsWithData/BaseTestWithData.php
The default behavior is still to do it in place, but if you pass the queueIndexing=true option to insert(), update() or delete(), it'll defer indexing using the ca_search_indexing_queue table.
There's a new "micro service" in index.php that runs the queue using a static function in the ca_search_indexing_queue model. It's not pretty to do it there but I figured we may not want to run this trough the full-blown MVC structure. The service gets called with a non-blocking async fsockopen() call during RequestHTTP::close(). There's also a CLI utility to run the queue by hand, just in case.
The queue processor uses semaphores to make sure only one processor is running at a time. I would love to change this to a non-blocking solution soon. I wasn't quite able to figure it out using flock(). The …
=> Move after-save search indexing into a separate process

app/lib/ca/BaseObjectLocationModel.php
+ `BaseObjectLocationModel` was `require`ing `ca_movements` and `ca_movements` was `require`ing `BaseObjectLocationModel` -- circular dependency.
+ It was not necessary to `require` `ca_movements` from `BaseObjectLocationModel` so this has now been removed.
=> Fix circular dependency.

app/lib/core/Parsers/TimeExpressionParser.php
This allows me to develop into a plugin a preparser for French Revolutionary Calendar dates.
The plugin would allow me to parse dates like "12 thermidor an II" (https://en.wikipedia.org/wiki/French_Republican_Calendar) before sending a normal date to the TEP class. This is only for input now.
In the future, it would allow the development of plugins for date entering from Hebrew, Islamic, persian, chinese calendars, probably with a special text mark to distinguish the calendar if the month names don't help. Going through plugins seems me a prudent way of digging into those.
=> NOJIRA : allows to hook TimeExpressionParser preprocess

app/conf/authentication.conf, app/controllers/system/AuthController.php, app/lib/core/Auth/AbstractLDAPAuthAdapter.php, app/lib/core/Auth/Adapters/ActiveDirectory.php, app/lib/core/Auth/Adapters/CaUsers.php, app/lib/core/Auth/Adapters/ExternalDB.php, app/lib/core/Auth/Adapters/OpenLDAP.php, app/lib/core/Auth/AuthenticationManager.php, app/lib/core/Auth/BaseAuthAdapter.php, app/lib/core/Auth/IAuthAdapter.php, app/lib/core/Controller/Request/RequestHTTP.php
This is a refactor of the new authentication code. There are three outcomes:
1. It actually works for ActiveDirectory configurations.
2. The post-authentication HTTP behaviour is fixed (see 0ce6f51 for details).
3. Improvements to the code style.
The major code style improvement is changing `IAuthAdapter` from a "static interface" to a normal interface that defines non-static methods. This means that the implementations have also changed to normal classes with instances, and `AuthenticationManager` holds a reference to an instance of the applicable implementation and calls methods on that instance, rather than calling static methods on a class identified by name.
I also created `AbstractLDAPAuthAdapter` which contains the LDAP functionality that is common between OpenLDAP and AD (which is …
=> LDAP authentication refactor

assets/ca/ca.bundlelisteditor.js
+ Fixes #224 
+ Lazily insert settings form HTML into the DOM when requested
by the user.
+ Uses a plugin-global (not instance-specific) cache for storing
the HTML, so there is a TODO about resolving namespace
conflicts, however this will only be a problem if used multiple
times on a single page.
=> Fix GitHub issue #224 - slow rendering of UI Screen Editor.

.htaccess
If you click on a XML the media, the caMediaDisplayContent can't as htaccess blocks it.
=> NOJIRA : allow xml display when clicking on a XML representation

app/lib/ca/BaseLookupController.php
NOJIRA : display homonyms in hierarchical browser
- changing vs_key to allow having duplicate names : as the keys were based on name, only one of the duplicates was shown, quite hard for the end user to figure out where his duplicates were hidden ; in order to correct that, I've added the item id as a suffix to the key
- adding strtolower to avoid having an alphabetical order with capital letters in the beginning of the list
- adding caremoveaccents to be sure words beginning with an accent are accurately displayed in the alphabetical order
---------
Hello Stefan & Seth,
This small PR handles different problems I had with hierarchies : 
- having an alphabetical order handling capitalized words differently
- pushing accentuated initials at the end of the alphabetical order
- not displaying …
=> NOJIRA : display homonyms in hierarchical browser

app/lib/core/Plugins/InformationService/ALANSL.php
Adds a new information service to look up names against the Australian National Species list web services. 
https://biodiversity.org.au/nsl/docs/main.html
Currently these services only include plant names, but animal names are on the roadmap.
Element Settings:
Autocomplete:
Extended Information
=> NOJIRA Feature/australian national species list information service attribute

app/conf/linked_data.conf, app/lib/core/Cache/CompositeCache.php, app/lib/core/Plugins/InformationService/BaseGettyLODServicePlugin.php, app/lib/core/Plugins/InformationService/BaseInformationServicePlugin.php, tests/lib/ca/AttributeValues/TGNInformationServiceAttributeValueTest.php, tests/testsWithData/get/AttributeGetTest.php
Now allows adding additional fields for get() availability and also allows traversing relationships recursively, so that you can crawl up/down broader/narrower relationships and pull in data (e.g. for search indexing) in the process.
The new stock linked_data.conf indexes preferred and alt labels for all skos:broaderTransitive relationships for both TGN and AAT. Results can get a little erratic and saving records with tons of new Getty associations can get sloooooow because we actually have to traverse these relationships and load the related resources. It's all cached however, so if a resource for whatever reason was loaded once, it'll get pulled from cache on the second attempt. The cache lasts for a week.
=> Getty linked data attribute type improvements

app/conf/app.conf, app/lib/ca/Attributes/Values/ListAttributeValue.php, app/lib/ca/BundlableLabelableBaseModelWithAttributes.php, app/lib/ca/Utils/CLIUtils.php, app/lib/core/BaseSettings.php, app/models/ca_metadata_elements.php, install/profiles/xml/testing.xml
This is a new feature that allows hiding certain bundles from user interface screens based on values selected for a list metadata element.
Basic documentation is here:
http://docs.collectiveaccess.org/wiki/Dependent_Field_Visibility
=> Dependent field visibility

app/version.php, install/inc/schema_mysql.sql, support/sql/migrations/122.sql
* Use LONGTEXT for `vars` and `field_access` columns in ca_user_roles
This fixes http://clangers.collectiveaccess.org/jira/browse/PROV-1443
=> PROV-1443 Fix Too many permissions make roles not save

app/helpers/displayHelpers.php, tests/testsWithData/get/DisplayTemplateParserTest.php
This is part of #241.  It does not shift the context to the related record (i.e. keeps focus on the interstitial; focus can be shifted using `<unit relativeTo="...">`).  It only adds the `rel` URL parameter to these links, which is consistent with the other similar link generated in the same method  (`displayHelpers.php` line 2718).
=> Fix missing `rel` URL parameter in generated links.

app/lib/ca/BundlableLabelableBaseModelWithAttributes.php
Fixes for PROV-1566 seem to have broken quick add, and also possibly the hierarchy browser due to undefined class `ca_metadata_elements`.
I've added the include in `__construct()` as a number of other files are included there.
=> NOJIRA fix fatal error class ca_metadata_elements is not defined

app/models/ca_data_importers.php
* `ca_data_importers::replaceValue()` trims the value before looking it up, so this should work around issues with inconsistent leading and trailing whitespace in source and destination data.
=> NOJIRA - Fix trimming of original value in `transformValuesUsingWorksheet`

app/models/ca_search_forms.php
* Previously search forms could not be tied to a particular subset of results
* Now you can add a hidden field such as `<input type="hidden" name="ca_objects.type_id" value="artwork"/>`
=> Add hidden field advanced search form bundle

app/lib/ca/Import/DataReaders/CSVDelimitedDataReader.php, app/locale/fr_CA/messages.po, app/locale/fr_FR/messages.po
Hi,
I was trying to import CSV data file to CA, but was stopped by the following error:
providence/support/bin$ ./caUtils import-data -m test_import -s 1.csv
CollectiveAccess 1.6.3 (126/GIT) Utilities
(c) 2013-2016 Whirl-i-Gig
Could not open source test.csv (format=)
providence/support/bin$ ./caUtils import-data -f CSV -m test_import -s 1.csv
CollectiveAccess 1.6.3 (126/GIT) Utilities
(c) 2013-2016 Whirl-i-Gig
Could not open source test.csv (format=CSV)
After looking around, I found that the problem was in `BaseDataReader->canReadFormat()`:
return in_array(strtolower($ps_format), $this->opa_formats);
But `CSVDelimitedDataReader->opa_formats = ['csvdelimited']` and 'csv' is not in `['csvdelimited']`.
Two ways to make code coherent with doc: 
- change the doc to make user use `csvdelimited` …
=> Fix: make CSVDelimitedDataReader formats coherent with caUtils import-data help message

app/plugins/statisticsViewer/statisticsViewerPlugin.php
There is an action permission that the plugin has, but the menu items do not include this action check so only become available to administrative users, not roles with the plugin enabled.
=> NOJIRA fix access permission to statistics viewer plugin

app/plugins/ULAN/ULANPlugin.php, app/plugins/WorldCat/WorldCatPlugin.php
* WorldCat and ULAN plugins had a change in d79f4e16acb090e7024239dd7484e63c25caedc0 which means that all other plugins
that implement `hookRenderMenuBar` do not fire
* See documentation about this under http://docs.collectiveaccess.org/wiki/Application_plugins#Hooks - menu plugins are required to
return a truthy value.
=> NOJIRA Fix allow other plugins to implement `hookRenderMenuBar()`

app/lib/ca/BaseEditorController.php
The previous commit [9bcae](https://github.com/collectiveaccess/providence/commit/9bcae6b8cc3e69b5e0faafb2ef1a84b953def7aa) not let a new object be created, contrary to initial message.
This fixes it and will only display wrong source error if the object has indeed a source different from the allowed sources of the user (if object is accessed by URL, for example), checking the source only if source exists. If not, then a new object is being created and will set the source value to user's default source.
=> PROV-2011 - Fix for new object creation with souce_access_checking

app/lib/core/Parsers/DisplayTemplateParser.php
Makes it possible to do:
```xml
<unit relativeTo="ca_places.hierarchy" hierarchyDirection="desc" maxLevelsFromBottom="2" delimiter=" &rArr; ">
^ca_places.preferred_labels
</unit>
```
=> Pass hierarchy parameters with units

app/conf/global.conf, setup.php-dist
`global.conf` variables cannot be overridden, so this is in lieu of changing the variable locally in that file. This way CA detects if it's using SSL from the server.
=> Support SSL by detection rather than global.conf

app/conf/assets.conf, setup.php-dist
Instead of hard-coding ssl connection status, let PHP auto-detect the https-status and set protocol accordingly.
Change "stamen" URL to https-version.
=> Auto detect https connection status in setup.config

app/lib/Search/SearchIndexer.php
* Prevents system getting crippled when indexing fails to complete properly.
=> NOJIRA Don't disable indexes in primary tables when reindexing content.

app/lib/Plugins/SearchEngine/ElasticSearch.php
* Slightly different parameters for performing the search for existing records.
* https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_search_operations.html#_scan_scroll vs https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_search_operations.html#_scan_scroll
Previously:
```
caUtils rebuild-search-index
```
resulted in:
```
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"parsing_exception","reason":"[match_all] query malformed, no start_object after query name","line":1,"col":23}],"type":"parsing_exception","reason":"[match_all] query malformed, no start_object after query name","line":1,"col":23},"status":400} in /path/to/ca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Conn …
```
=> Fix single table indexing for ElasticSearch 5.x

app/lib/ca/Service/ItemService.php
This prevents the error:
> Cannot add or update a child row: a foreign key constraint fails (ca_object_labels, CONSTRAINT fk_ca_object_labels_locale_id FOREIGN KEY (locale_id) REFERENCES ca_locales(locale_id))
by using the default locale setting when one is not passed in the request.
=> Use default locale for services when not provided

app/lib/BundlableLabelableBaseModelWithAttributes.php
Adding existing media representations in objects is not working. When searched for an existing media representation a list of existing media shows up correctly, however making a selection and saving object does not add the selected media representation to the object. This fix solves this problem.
previous pull request: https://github.com/collectiveaccess/providence/pull/336
=> add existing media representation

Vagrantfile
The current 1.7.8 version of providence doesn't work with the provided Vagrantfile.
So I've updated it to use php7.2 with the required — at install at least — dependencies.
The current Vagrantfile with php5.5 fails with a 500 error (I suspect something involving vendors...).
Also tried with php7.3 and that fails at the installation page 2 (only creates some tables and then freezes).
=> Update Vagrantfile to use php7.2 on ubuntu xenial

app/helpers/utilityHelpers.php
* The method description says it's designed to strip weird noncharacter data.
* This change only removes values if they are actually set.
* Means that SimpleAPI can return blank values in a deterministic way.
=> NOJIRA Don't remove empty values from arrays in caSanitizeArray

app/lib/Plugins/SearchEngine/ElasticSearch/FieldTypes/Intrinsic.php
* Don't index as idno by default - in_array required strict checking.
=> NOJIRA Fix full text indexing of entity labels and other fields.

app/controllers/administrate/setup/ElementsController.php
* ERROR --> DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lambda WHERE count > 1' at line 5
This is an AWS Aurora database.
=> Fix weird reserved word error on AWS.

app/lib/Attributes/Values/DateRangeAttributeValue.php
Use the current global locale to initialize `TimeExpressionParser`
See https://collectiveaccess.atlassian.net/browse/PROV-2795
=> PROV-2795 Dates are shown on the wrong locale

app/conf/app.conf, app/helpers/logHelpers.php, app/lib/Utils/CLIUtils/Media.php
I had to verify that `reprocess-media` command line tool was running properly and I made this patch.
I have mimic the behaviour of other commands and also took the opportunity to refactor code to create loggers, so there is also the opportunity to refactor other code pieces in the future, and avoid boilerplate code (see new function `caGetLogger`).
Hope it will be useful for other people too!
=> Allow logging on reprocess media

app/helpers/htmlFormHelpers.php, tests/helpers/HtmlFormHelpersTest.php
I configured media_processing rules to allow a tile size of 512px and then images are shown with disordered tiles.
I traced the error to the way the tile viewer is configured in `htmlFormHelpers.php`, and there is a hardcoded value of `256` for the tilesize of the viewer.
I also added some tests.
=> BUG Media viewer does not use image tile size.

install/profiles/xml/default.xml
There is an intrinsic attribute `ca_entities.lifespan` as per https://github.com/collectiveaccess/providence/blob/9f4a96639f80da0e31e9acc9b76bb8935f8c36b6/app/models/ca_entities.php#L109-L117
And there is an additional `lifespan` metadata attribute on `default.xml` profile. 
This PR removes the second one.
=> FIX Remove duplicate for `lifespan` intrinsci attribute.

app/helpers/utilityHelpers.php, tests/lib/AttributeValues/LCSHQueryTest.php, tests/lib/AttributeValues/WikipediaInformationServiceAttributeValueTest.php
Related to #400.
A Web service is an external dependency. In case it fails I suggest marking the test as incomplete.
=> Mark tests as incomplete when web service lookup fails.

tests/setup-tests.php
Bootstraping file for tests at `setup-tests.php` loads `setup.php` file.
In case you are developing locally, it will use your local configuration too, so tests might break, for instance, if you setup a timezone in Europe, or any other local configuration.
A workaround is already in place in `.travis.setup.php` file: it loads vanilla setup from `setup.php-dist`.
Related to #400.
=> Force loading a clean setup from the dist file.

app/conf/external_applications.conf, app/lib/Plugins/Media/ImageMagick.php, tests/conf/external_applications.conf, tests/lib/Plugins/Media/ImageMagickTest.php
Second attempt for this PR, previous one included a mix of commits not related to it.
Define a configuration item in `external_applications.conf`, like this: `imagemagick_<COMMAND_NAME>_args` per command.
For example, for `convert` command, use 
```
imagemagick_convert_args = -limit thread 1
```
As of now it only allows arguments on the ImageMagick media class. It is pending a refactor of TilePicParser class to use this feature.
With a bit of refactor, new class `CommandConfiguration` can be promoted to `BaseMediaPlugin` class, and the feature will be available to subclasses.
=> Allow additional arguments for ImageMagick external applications

support/bin/caUtils
Also removed "--help" option, since it was never used.
Now when called with no valid command:
```bash
vagrant@ubuntu-xenial:/vagrant$ php7.2 support/bin/caUtils zz
CollectiveAccess 1.7.9 (162/GIT) Utilities
(c) 2013-2020 Whirl-i-Gig
Global options
--hostname (-h)     Hostname of installation. If omitted default installation is used.
--setup (-s)        Specify the path to an alternate setup.php.
Configuration
...
```
When calling `help` with no valid command, it shows global options too:
```bash
vagrant@ubuntu-xenial:/vagrant$ php7.2 support/bin/caUtils help zz
CollectiveAccess 1.7.9 (162/GIT) Utilities
(c) 2013-2020 Whirl-i-Gig
No help is available for "zz"
--hostname (-h)     Hostname of installation. If omitted default installation is used.
--setup (-s)        Specify the path to an …
```
=> Small refactor on caUtils, solve some typos and show global options

.travis.yml, tests/database_setup.sh, tests/profile_setup.sh
Allow caching `composer` and database for faster env setup, test time reduction of about 30-50%, with same reliability.
It uses Travis-CI caching facility for caching:
- `vendor` folder. It will copy `composer.lock` file to `vendor` folder too, so restoring the configuration is extremely fast.
- profile database dump. It will dump database after profile installation. It will load it again on the next execution. It will speed database creation (creating relationships and other tables are really slow). If you would like to skip profile database caching, set env variable `SKIP_CACHED_PROFILE` to any non-empty value.
=> Allow caching test env for faster test execution

app/helpers/importHelpers.php, app/helpers/mediaPluginHelpers.php, app/helpers/utilityHelpers.php, app/refineries/EADCollectionHierarchyBuilder/EADCollectionHierarchyBuilderRefinery.php, app/refineries/collectionIndentedHierarchyBuilder/collectionIndentedHierarchyBuilderRefinery.php, tests/conf/external_applications.conf, tests/helpers/ImportHelpersTest.php, tests/helpers/MediaPluginHelpersTest.php, tests/helpers/UtilityHelpersTest.php, tests/phpunit-coverage.xml
This PR includes a fix for #409 (broken regexp match).
While adding the test for it, I realized I may improve testing coverage, and I extended the PR to also include a refactor of `ImportHelpersTest`.
It also includes a cherry-pick at dc0ef584a1172dae7d6f25bc5d4b52a88eda3cdd by @collectiveaccess for pending TODOs on importHelpers, I included it to make sure tests are more robust.
=> Improve coverage of tests for import helpers.

app/helpers/CLIHelpers.php, support/bin/caUtils, tests/helpers/CliHelpersTest.php
I realized that short alias for global options may conflict with sub-commands options, for example, `import-media` source option also uses `-s` as a short alias (a PR will follow also on `import-media` params later).
In order to avoid the conflict, I removed sort aliases on global options.
In the process I realized:
* the right syntax for a long-only option is `longoption[-=]s`, so I also updated the code accordingly.
* former `_formatCmdOptions` function will best fit into a helper file. I refactored it a bit, using code borrowed from Zend GetOpt implementation.
* there were no tests on the former `_formatCmdOptions`, so I add them in this PR.
=> Remove short alias on global options to avoid conflicts on subcommands.

app/lib/BatchProcessor.php, app/lib/Utils/CLIUtils/ImportExport.php
Several fixes on the code:
1. refactor common regex
2. solve some undefined variables.
3. mark pending undefined variable for transaction, it is not clear to me how to solve it: uncomment the code or remove commented code and variable.
4. fix lower case comparison
5. rename command line options. Zend treats aliases with more than 1 letter with single dash as a cluster of single letter options (`-dmoi` is parsed as 4 options: `-d`, `-m`, `-o` and `-i`), not as a single command.
=> Several fixes on import media

app/helpers/searchHelpers.php, tests/helpers/SetSearchHelpersTest.php, tests/testsWithData/BaseTestWithData.php
While running a query like "centro~" the server crashed with an HTTP 500 Error.
Tracing the cause, it was due to an infinity recursion on `caSearchIsForSets`, because there was no stopping condition when subqueries were fuzzy.
Added some tests too.
=> FIX Fuzzy search caused infinity recursion

app/conf/app.conf, app/helpers/navigationHelpers.php, app/lib/Controller/RequestDispatcher.php, composer.json, install/inc/Installer.php, install/index.php, tests/conf/app.conf, tests/lib/Controller/DisableGzipTest.php
It also includes 
* code cleaning on `app/helpers/navigationHelpers.php` and the installer.
* disable gzip compression on web install script.
Closes #427
=> #427 Allow configuring which controllers will not use compression.

app/controllers/lookup/ListItemController.php
Code to read "max" parameter controlling maximum page lengths in hierarchy browser level loads had been removed. This commit restores it, greatly improving performance and display of very long hierarchy levels.
=> NOJIRA Restore parameterized length limit

app/lib/BaseModel.php, app/lib/BatchProcessor.php, app/lib/BundlableLabelableBaseModelWithAttributes.php
Minor improvement that will link existing representations to a target record if no other relationships exist. This is useful in cases where you want to reimport object records (for example), but want to avoid reimporting the representations.
=> PROV-2902 Implement representation reuse

app/helpers/expressionHelpers.php, app/lib/Parsers/ExpressionParser/ExpressionGrammar.pp, app/lib/Parsers/ExpressionParser/ExpressionVisitor.php
• Add boolean literals to simplify testing of function return values
• Add isDateRange() function to test whether a date is single or a range (useful for EAD, where single dates are handled differently than ranges)
=> PROV-2910, PROV-2911 Improvements to expression parser

app/lib/BaseModelWithAttributes.php
Name of container was being passed through and forcing all sub-elements to have the same name.
=> NOJIRA Ensure container sub-fields are named properly on forms

app/models/ca_data_exporters.php
Some exporter options would not be applied in specific display cases. This change propagates options defined in a mapping to those cases.
=> NOJIRA Pass through options for display

app/helpers/importHelpers.php
Some exporter options would not be applied in specific display cases. This change propagates options defined in a mapping to those cases.
=> NOJIRA Set lot pref label when set in mapping

app/helpers/importHelpers.php, app/lib/IDNumbering/MultipartIDNumber.php, app/lib/IDNumbering/SMFMultipartIDNumber.php, app/lib/IDNumbering/UUIDNumber.php
To improve import of hierarchies where the numbering scheme reflects the hierarchical structure (common when dealing with collection-level records), this PR adds the following options:
1. "normalize": provides normalization of numbers such that an abbreviated number in the data source is intelligently padded out to full length. Eg. If the numbering scheme for a folder-level collection record is 6 numbers (Ex. 2020.5.3.3.8.1), the last of which is auto-generated, but the data fewer numbers (Ex. 2020.5.3.3), this option will pad out the "missing" numbers with 1's. Thus 2020.5.3.3.% in the mapping becomes 2020.5.3.3.1.% for import. (This sort of mismatched data is occurring in Riverside, for example). This option should require explicit activation in the mapping – by default is should be …
=> PROV-2914 Add new importer options for "parents"

app/lib/BaseModelWithAttributes.php
Null values on their own will not be set using BaseModelWithAttributes::editAttribute() as nulls are not considered changed values in the testing it performs on input. This change makes editAttributes() treat null values as significant when trying to determine if there are changed values to apply.
=> PROV-2915 Make editAttributes() consider null as target value of change

app/models/ca_bundle_displays.php
Add option to limit number of related items show in a display bundle placement. This is useful for placing an upper limit on the length of a related placement in a display, limiting space requirements and time to generate.
=> PROV-2916 Add numPerPage option

app/helpers/importHelpers.php, app/lib/BaseModel.php
Change allows use of ^PARENT_IDNO in splitter "attributes" blocks when used in conjunction with "parents" block. ^PARENT_IDNO will be set to the lowest-level record created in the "parents" block.
=> PROV-2914 Add PARENT_IDNO tag support to generic splitter

app/lib/Attributes/Values/DateRangeAttributeValue.php, assets/jquery/jquery-ui/i18n/jquery.ui.datepicker-nl_BE.js
• Use user preferred locale when parsing dates, falling back to default locale when required. Previous behavior was to use the system default locale in all cases.
• Add date picker translation for Flemish
=> PROV-2917 Use user preferred locale when parsing dates

app/lib/Media.php
In cases where the file mimetype or extension values are null the caching library will throw an exception. This change catches those null invocations and returns null without attempting to access the cache.
=> NOJIRA Test params to value to avoid cache errors

app/lib/Parsers/DelimitedDataParser.php
NOJIRA With conversion of delimited data parsing to fgetcsv() support for import of files using Mac line endings is broken on some syatems. This patch resolves this by enabling auto_detect_line_endings at run time while parsing files. It restores the server-configured value after the parse.
=> NOJIRA Fix for broken delimited data parsing of data with mac line breaks

app/conf/annotation_types.conf
The annotation editor fields for start and end time code used for time-based media were too small for most timecode. This commit increases the field size to a comfortable width.
=> NOJIRA increase field size to avoid spacing issues

app/lib/BundlableLabelableBaseModelWithAttributes.php
The user preference controlling if idno is duplicated when a record is duplicated has no effect on the duplication process. This change enables enforcement of the preference.
=> PROV-2918 Honor idno duplication preference

app/lib/Plugins/Media/Office.php
Embedded metadata is not extracted from Office (Word, Excel or Powerpoint) files when uploaded as media. This PR adds support for running Exiftool over these files.
=> PROV-2919 Use EXIFTOOL to extract metadata from Office files

app/lib/BaseModel.php
Normally only fields that change are included in change log snapshots. This behavior saves space but can cause problems with data replication. This PR changes logging to log the full attribute or attribute value record each time a change is made.
=> PROV-2920 Do full snapshot for ca_attributes and ca_attribute_values

app/conf/datetime.conf, app/lib/Parsers/TimeExpressionParser.php
This PR adds a new "dateFormat" mode to force output of year part of date only. This is useful for certain data export or display situations where only years are relevant.
=> PROV-2921 Add yearOnly date format

app/lib/BatchProcessor.php
This PR fixes an issue where when attempting to reuse an existing representation a fatal error occurs because the relationship between object and representation already exists.
=> PROV-2902 Catch case where reused relationship already exists and skip

app/helpers/logHelpers.php, app/lib/Utils/CLIUtils/ImportExport.php, app/models/ca_data_importers.php
Add Excel-based detailed logging of field-level import errors. Errors are broken out by field, with each field with errors having its own worksheet. Error output includes date/time of error, row in data set, idno of record being imported, error message, values that caused error and, in some cases, additional notes.
=> PROV-2869 Add detailed field-level logging

app/models/ca_search_indexing_queue.php
Change load size for search indexing queue to maximum 100 indexes, from 1000.  This helps to avoid MySQL query failures on some systems due to memory exhaustion.
=> NOJIRA Change search indexing load increment size to 100

app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/Controller/Request/RequestHTTP.php, app/models/ca_data_importers.php
Improvements to detailed logging of field-level errors in data importer:
• Refactor stop-on-error handling
• Don't write detailed log when no errors occur, as the result is an invalid Excel file
• Add missing parameter when formatting values for log
=> PROV-2869 Improve detailed logging

app/lib/Attributes/Values/ListAttributeValue.php, app/lib/BatchProcessor.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/Utils/CLIUtils/Configuration.php, app/lib/Utils/CLIUtils/ImportExport.php, app/lib/Utils/CLIUtils/Maintenance.php, app/models/ca_data_importers.php, app/plugins/ResourceSpace/controllers/ImportController.php, app/plugins/ULAN/controllers/ImportController.php, app/plugins/WorldCat/controllers/ImportController.php, support/bin/caUtils
Improve detailed import logging:
• Use CSV as detailed log format as XLSX causes performance and memory issues
• Log attribute set()-level errors (a prime use-case for detailed logging)
• Convert primary import method from static to instance to simplify access to logging instances
These changes are precursors to a much-needed significant refactoring of the data importer.
=> PROV-2869 Improve detailed logging content; use CSV as detailed log format

app/conf/search.conf
Help to avoid max-allowed-packet errors on some systems
=> NOJIRA Smaller default for max_indexing_buffer_size (5000) 

app/lib/Search/SearchEngine.php
When applying rewrites the search engine will look for rules for the specific table, but fall back to applying any rule if no specific ones exist. This is generally undesirable and confusing, although there was a reason for it for one user way back when. This PR ensures that only specific rules are used, which is the general case..
=> NOJIRA When rewriting searches only apply rules configured for the current table

app/lib/Utils/CLIProgressBar.php, app/lib/Utils/CLIUtils/Media.php
PR addresses two issues raised by recent changes:
• Remove extra declaration of "quiet" option on reprocess-media
• Remove reference to old nurses window
=> Fix minor caUtils issues 

app/lib/ExternalExportManager.php, app/lib/Plugins/ExternalExport/BaseExternalExportFormatPlugin.php
PR makes the following improvements to the external export system:
• Force default media file name when no "original" name is defined. This prevents writing of null names into ZIP-based archives, which are effectively unretrievable.
• Add "access" trigger to pull all records with a specific access value on trigger
=> PROV-2892 Improvements to external export system

themes/default/views/mediaViewers/pdfjs.php
PR replaces hardcoded path that assumes application is running in the web server root with a dynamically generated one.
=> PROV-2931 Remove hardcoded path in PDF.js support

app/conf/app.conf, app/helpers/displayHelpers.php
PR adds new app.conf settings that allow setting of default display templates for relationship bundles such as "ca_objects" and "ca_entities" in editor user interfaces. Previously, defaults were derived from the templates used to format type-ahead lookups, which weren't always suitable for defaults. With this PR, the template in the new setting is used and, if not present, values for lookups (ie. the old behavior) are used.
=> PROV-2935 Add new app.conf setting for default display templates for editor relationship bundles

app/lib/Utils/CLIUtils/ImportExport.php
PR fixes issue in caUtils import/export handler where static call is used where instance is now required when getting error messages.
=> PROV-2869 Use instance, not static

app/lib/Search/SearchResult.php, app/models/ca_data_exporter_items.php, app/models/ca_data_exporters.php
PR added new stripTags export mapping option, that will remove all HTML tags from exporter output. Also implements a generally available stripTags option for BaseModel::get()
=> PROV-2937 Add stripTags option to remove HTML from export output 

app/helpers/printHelpers.php, composer.json
* Running on docker using an Alpine PHP image resulted in warnings and failed globbing.
* https://github.com/docker-library/php/issues/719
=> NOJIRA Replace glob call with Zend\Stdlib\Glob::glob

app/lib/BaseModel.php
PR adds constant allowing disabling of history tracking value updates on update of model instance. This can be useful when performing bulk imports as the updating is relatively slow.
=> NOJIRA Add __CA_DONT_UPDATE_HISTORY_TRACKING_CACHE__ flag

app/lib/ExternalExportManager.php
PR adds external export option to require media to be related to a record for it to be exported. This oddly specific flag is required by the CTDA.
=> PROV-2892 Add option to skip records without media (CTDA requirement)

app/lib/Auth/Adapters/Okta.php, app/lib/Controller/Request/RequestHTTP.php
PR addresses issue where access using urls with trailing double slashes (Ex. http://myarchive.org//) can cause infinite recursion and eventual memory exhaustion. PR does the following:
• Rewrites urls with double slashes to use single slashes
• Ensures Okta auth plugin does not redirect to a double-slash url on login.
(Also uses last page url for Okta destination url).
=> PROV-2938 Urls with trailing  double slash ("//") can cause crashes

app/controllers/administrate/setup/ElementsController.php
PR adds missing quote in SQL query, resolving issue introduced by work to support MySQL 8. This typo would cause a SQL error when attempting to reposition fields within and editor UI container bundle.
=> PROV-2788 Add missing quote around rank field

app/lib/BaseModel.php, app/lib/LabelableBaseModelWithAttributes.php
PR adds "start" option to BaseModel::find(); in conjunction with existing "limit" parameter this provides a mechanism for paging. Also moves application of start and limit to query, rather than chopping full result set after it's pulled from the database. This greatly improves performance with large datasets.
=> NOJIRA Add "start" option to find(); apply start and limit at query level

app/lib/Search/SearchIndexer.php
PR resolves issues in indexing of relationship counts for search:
• Now indexes zero relationship counts; previously these were omitted making it impossible to search for records with no relationships 
• Only emits index entries for the full count, rather than incremental counts done previously. This means that a search on the a count will now only return those records with that count, rather than all records with that count or great. Range queries may be used to find records with a count meeting or exceeding a threshold.
=> PROV-2939 Resolve relationship "count" indexing issues

app/lib/Search/SearchResult.php
PR fixes capitalization error in option name that breaks the "returnPath" option on get(). This option forces media values to be returned as an absolute file path rather than a tag or url. It is often useful when working with media in PDF output, where absolute paths may be more reliable than URLs in some cases.
=> NOJIRA fix typo that breaks BaseModel::get() "returnPath" option for media

app/models/ca_bundle_displays.php
PR forces use of media paths rather than URLs when "forReport" option is set. Paths seems to be more reliable than URLs (which rely upon working server-side DNS) when generating PDFs.
=> NOJIRA force use of media paths rather than URLs when "forReport" option is set

app/helpers/utilityHelpers.php, app/lib/Import/DataReaders/ExcelDataReader.php, app/lib/Plugins/Media/PDFWand.php
PR fixes a handful of importer issues:
• Excel data reader now returns null when an invalid column specifier is used rather than propagating a PHPSpreadsheet exception
• caGetDirectoryContentsAsList() now returns an empty array rather than a messy warning if the directory does not exist
• PDFWand media importer now supports all image transformations as pass throughs, avoiding errors when previously unsupported image options were set.
=> Misc import fixes

app/helpers/exportHelpers.php
PR adds ".pdf" to download file name, resolving file naming issue in Google Chrome.
=> NOJIRA add PDF extension to downloads

app/helpers/importHelpers.php
PR propagates "ignoreType" option to DataMigrationUtils::_getID() so it can be applied.
=> PROV-2940 Don't ignore the ignorers

app/conf/app.conf
PR modified default template relationship bundle template for storage locations to display full hierarchy path, which is the most commonly requested format.
=> PROV-2935 Make storage location default show full hierarchy by default

app/lib/BaseEditorController.php
PR addresses regression caused by new default behavior introduced ion PROV-2890 that prevents sub-types below the first sub-type that is enabled from showing in menus. The default is now to show all sub-types, in line with previous behavior.
=> PROV-2890 Sub-types in menus don't show below first enabled type

assets/jquery/superfish.js
PR fixes issue where menus near right side of window toggle between moving downward (good) and going off screen (bad). Now always move downward.
=> PROV-2944 Don't cut off menu when near right hand side of window

app/models/ca_data_importer_items.php, app/models/ca_data_importers.php
PR adds six new data importer mapping options enabling skipping of mappings, groups or rows when any one or all values in a list of placeholder values are empty. This provides additional flexibility in skipping import of empty values without having to resort to writing expressions.
=> PROV-2945 Implement options for skipping mappings/groups/rows when placeholder values are empty

app/lib/Utils/CLIUtils/Configuration.php, install/inc/Installer.php
* Large collections have large indexes which can take days to reindex. A profile update is normally not destructive, so doing a full reindex seems OTT.
relates to https://github.com/collectiveaccess/providence/pull/538
=> NOJIRA Don't wipe the ES index on profile updates, just write the config changes.

app/models/ca_metadata_elements.php
* Previously updates to the ES mapping were only shipped at  most once every 24 hours. Now we can queue them up to be shipped at next index.
* This reulted in a problem that if a user creates a new field and then saves data, the data mapping is guessed by ElasticSearch unless it's been specified.
* Now we queue ES mapping update.
=> Clear ElasticSearch mapping when saving metadata elements.

app/helpers/searchHelpers.php, tests/lib/Search/ElasticSearch/FieldTypes/DateRangeTest.php
PR fixes issue where incorrect "start" date is indexed in ElasticSearch for "before xxxx" date expressions. Also adds missing test case for this formulation.
=> PROV-2951 "Before" dates not working with ElasticSearch

app/conf/services.conf, app/lib/Controller/Request/Session.php
This make REST API session lifetime configurable in services.conf instead of hard coded 2 hours. Default is still 2 hours.
=> Make REST API session lifetime configurable

app/models/ca_data_exporters.php, assets/ca/ca.bundleupdate.js
PR improves the data exporter repeatmappings system. Repeatmappings allows one to reuse existing export mappings in multiple locations in an export. This is useful for export formats where the same data structures are used in multiple locations. (For instance, in EAD where the same record structure is used for arbitrarily deep hierarchies.)
The current implementation only allows reuse of mappings that are actually in-use parts of the export format, and only after they have been defined. That is, anything you need to repeat needs to be defined earlier in the format than where it's referenced and will be used as part of the export format in that first location.
This PR implements a new mapping  "template" row type (in addition to the current "mapping", "constant" and "variable") that allows …
=> PROV-2954 Implement "template" row type for data exporter; fix issue that may prevent live update of editor bundles

app/helpers/importHelpers.php
PR modifies idno normalization in data importer hierarchy builder to use multipart id numbering element default value for inserted element values rather than always inserting "1". Since "1" is typical, it remains the default in the absence of a default value set in multipart_id_numbering.conf.
=> PROV-2914 idno normalization should use default value for element when specified

app/lib/RepresentableBaseModel.php
PR fixes issue where in-editor sorting of bundle contents only sorts first page of results rather than the entire result set.
=> PROV-2827 Sort full set of relations

app/lib/Export/ExportFormats/ExportXML.php
PR fixes issue where XML output is not properly escaped when the stripCDATA option (aka. don't use CDATA blocks) is set. When CDATA blocks cannot be used escaping is now performed.
=> PROV-2955 Escape chars when stripCDATA is set

app/lib/Plugins/ExternalExport/Output/SimpleZip.php
PR fixes issue in external export framework where derivate filenames with OS-specific special characters (eg "/") cause fatal errors. We now strip all non-alphanumeric chars from file name to ensure interoperability across storage media and OS's.
=> PROV-2892 Strip problem chars from file names

app/lib/Search/SearchResult.php
* Previously this would only return string values, but templates are generally processed to return as array, so this makes it possible to return the values.
Now you can use values like:
```
^ca_objects._guid
```
in display templates.
=> NOJIRA Allow `_guid` values to be returned in display templates.

app/lib/Controller/Request/Session.php
My first PR #551  to Providence was horribly broken as it broke REST API sessions. I assumed that Configuration::load(); would load ALL config files.
This PR actually reads "services.conf" file and therefore makes REST API session lifetime configurable via "api_session_lifetime".
Sorry!
=> fix PR #551 REST api session lifetime

app/helpers/utilityHelpers.php, app/lib/BaseModel.php, app/lib/LabelableBaseModelWithAttributes.php, tests/testsWithData/find/FindTest.php
PR adds support for BETWEEN range queries on scalar values in BaseModel::find() and LabelableBaseModelWithAttributes::find()
=> PROV-2957 Implement BETWEEN operator in find()

app/helpers/displayHelpers.php
PR alters download file naming to strip file extensions off of generated download file names before appending current extension. The avoids ugly double extensions.
=> PROV-2860 Strip file extensions off of generated download file names 

app/models/ca_data_importers.php
PR prevents warnings when using parent_as_subject mode and content tree does not include subject data (rare but it can happen when reimporting over existing data); also slight improvement in logging.
=> NOJIRA prevent warnings; slightly improve logging

app/helpers/importHelpers.php, app/helpers/preload.php, app/lib/Attributes/Values/LCSHAttributeValue.php, app/lib/Browse/BrowseEngine.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/HistoryTrackingCurrentValueTrait.php, app/lib/Import/BaseRefinery.php, app/lib/Media.php, app/models/ca_editor_ui_screens.php, app/models/ca_sets.php, themes/default/css/base.css, themes/default/views/manage/set_list_html.php
PR addresses various issues:
PROV-2965 search issue when using terms containing ampersands passed through the browse as a _search facet. HTMLPurifier will encode ampersands. This change unescapes them prior to use.
PROV-2959 don't apply regexes to splitter option settings
PROV-2960 Use first match for LCSH lookups in import context
PROV-2961 Add current location support for related list bundles
PROV-2962 Clean up caMultiplagePreview tmp files generated by PDFWand plugin
Other: truncate long paths in media importer and set editor, add creation date to set list feed, extend autoloading to Media libs
=> PROV-2959,2960, 2961, 2962, 2965 Various bug fixes 

app/lib/Parsers/TilepicParser.php
PR adds additional rotation to properly orient tilepic tiles when EXIF orientation flag indicates 180 degree rotation. For some reason, recent Gmagick versions fail to retain 180 degree rotation when clone() is used. Clone is used on Gmagick handles when generating tiles. The fix is to add a per-slice 180 degree rotation. Oddly, 90 and -90 degree rotations _do_ persist across clone()s.
=> PROV-2887 Patch to properly handle 180 degree orientation flip 

assets/ca/ca.relationbundle.js
We found that the autocomplete lookup field for related fields (related collections, related entities,..) had side-effects: when the dropdown was shown, and the user scrolled outside this list, the body scrolled and the list got detached from the input field.
It appeared that the jquery autocomplete had no specific element referenced as the appendTo, thus defaults to appending it to the body.
I specified the appendTo as the 'parent' container via options.container option, and that keeps the dropdown in situ.
=> PR-572 Anchor lookup lists

app/helpers/importHelpers.php, tests/helpers/ImportHelpersTest.php
Refactor testing code to substitute remote API calls to AAT by mocks. It will reduce external dependency on AAT API service.
Nevertheless, I kept one of the end-to-end tests to make sure there is a test that properly tests AAT service is up and running.
=> Refactor to use AAT query mocks

app/lib/Parsers/TimeExpressionParser.php, tests/lib/Parsers/TimeExpressionParserTest.php
PR corrects behavior when normalizing BCE dates to century. Previous behavior tagged on an extra century. Eg. 100 BCE - 100 AD resulted in normalization of 2nd century BCE, 1st century BCE, 1st century AD, 2nd century AD, where 2nd century BCE is not correct.
Also adds tests for century normalization, which had been omitted for some reason.
=> PROV-2967 Normalize BCE dates correctly

app/conf/authentication.conf, app/lib/Auth/Adapters/Shibboleth.php
PR generalized attributes used to create new user accounts using a configurable mapping in authentication.conf, and standardizes naming of Shibboleth-related authentication directives.
=> PROV-2976 Use attribute mappings for Shibboleth authentication

app/lib/Parsers/DisplayTemplateParser.php, app/lib/Search/SearchResult.php
PR changes the behavior of the display template unit "filterTypes" option. The display template parser <unit> tag can filter hierarchies based upon type using the "filterType" option. Currently types specified here are expanded hierarchically, which can lead to hard-to-debug effects. The behavior should be changed to not expand types and require desired types to be explicitly specified.
=> PROV-2978 Don't expand hierarchically

app/lib/Parsers/DisplayTemplateParser.php, app/lib/Search/SearchResult.php, app/models/ca_data_exporter_items.php, app/models/ca_data_exporters.php
PR adds per-mapping option to data exporter to strip new line values from exported text. This is useful for compatibility with some data consumers. Eg. consumers that choke on returns in values in CSV files, even when properly escaped, like IPT.
=> PROV-2979 add strip newlines option to data exporter

app/conf/search_indexing.conf, app/lib/Plugins/SearchEngine/SqlSearch.php, app/lib/Search/SearchIndexer.php
In earlier days the search indexer supported INDEX_IDNO_PARTS and IDNO_DELIMITERS options which indexed identifier in parts based upon specified delimiters. For example, when INDEX_IDNO_PARTS was set and IDNO_DELIMITERS set to a list including ".",  2010.002.35 would be indexed as the discrete values 2010, 002 and 35.
These options were dropped when INDEX_AS_IDNO was added (although references to the old options were left in search_indexing.conf, causing confusion). INDEX_AS_IDNO uses multipart_id_numbering.conf configuration to index identifiers in a manner consistent with their configured format. 
INDEX_AS_IDNO is superior in that it requires less configuration and indexes progessively, which is usually preferred. Thus 2010.002.35 is indexed as 2010.002.35, 2010.002 and 2010.
There are …
=> PROV-2988  Add IDNO_DELIMITERS search indexing option

app/lib/Plugins/SearchEngine/ElasticSearch.php
* Prior to this when trying to connect to an instance on SSL this would lead to an exceptoin as ES uses http by default.
=> NOJIRA Support SSL for ElasticSearch hosts.

themes/default/views/batch/metadataimport/batch_results_html.php
Per our previous conversation, with explicit strings for translation. Curiously, either the code was confused or I am, as the various 'status' values listed originally seem to pertain to batch media imports and not to metadata imports. If this is ok I can fix themes/default/views/batch/mediaimport/batch_results_html.php  which already contains a similar non-extractable _t() string.
=> Localize metadata import result status

app/lib/Plugins/InformationService/VIAF.php
Hi,
the query parameter for this guzzle request to viaf was set in a separate array and should be nested in the options array. 
The old code resulted in a 500 error at VIAF, now results in the resultset by VIAF
=> change guzzle query request array

app/lib/Search/SearchResult.php
PR enables the SearchResult::get() filterTypes option, and consequently the display template parser filterTypes attribute, to be passed as a comma or semicolon separated list. Currently it is used as a string, which limits filtering to a single type.
filterTypes is used to control which record types are returned when pulling data from a hierarchy.
=> NOJIRA Allow filterTypes option to be comma or semicolon separated list

app/controllers/find/QuickSearchController.php, app/lib/Search/QuickSearch.php
PR adds possibility of search/display of object representation records in quick search, if so configured. Default settings are unchanged and do not include representations (most users will not want them in quick search).
=> PROV-2994 Add object representations to quick search

app/models/ca_editor_ui_screens.php, install/profiles/xml/base.xml, themes/default/views/bundles/ca_object_representations.php
PR addresses two minor issues in the media representation (ca_object_representations) bundle:
- When representation type is included in the in-line editing form it lacks a label
- Bundle mode (classic vs new) is not retained during first save of newly placed bundle
=> PROV-2996, PROV-2997 Representation bundle fixes

app/conf/app.conf, app/helpers/mediaPluginHelpers.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/Plugins/Media/Gmagick.php
PR resolves issue where Gmagick based media processing outputs distorted derivatives when EXIF orientation tags are set. Issue involves stripping EXIF metadata from derivatives to prevent undesired rotation by consuming applications.
=> PROV-2999 Fix for distorted derivative images when using Gmagick and EXIF orientation tag is set

app/lib/Plugins/Media/Audio.php
PR addresses issue raised with the migration to composer-based getID3() support for WAV files is broken. This is due to a change in reported mimetype for this particular format. Other formats (AIFF, MP3) are not affected.
=> PROV-3002 Update mimetype used for WAV

app/lib/Parsers/TimeExpressionParser.php
PR added support in date/time parser for dates coded  in the form YYYY-MM/YYYY-MM (Ex. 1967-03/1967-04 or 1952-10/1952-11) which are valid ISO 8601 Extended Date Time Format.
=> PROV-2969 Add support for year/month ISO ranges

app/conf/datetime.conf, app/lib/Parsers/TimeExpressionParser.php, tests/lib/Parsers/TimeExpressionParserTest.php
PR adds new year-month-day (ymd) date formatting option. This allows for the requested YYYY.MM.DD input and display format by using dateFormat=ymd in conjunction with dateDelimiter=.
The ymd format is similar to the existing iso8601 format, save the it honors date formatting options such as custom delimiters through the dateDelimiter option. The iso8601 format ignores all such options by design to ensure conformity to the standard.
=> PROV-2971 Make all dates display as YYYY.MM.DD 

app/models/ca_data_importers.php
PR adds four new existing record policies to the data importer: merge_on_id, merge_on_id_with_replace, overwrite_on_id, skip_on_id
These policies merge using internal CollectiveAccess primary key id integers. They exist for those odd times when your data is using those ids.
=> PROV-2974 Add existing record policies that operate on CollectiveAccess primary key ids

app/conf/annotation_types.conf
PR updates annotation types config to allow annotation editing on WAV files using "new" mimetype (audio/wav)
=> PROV-3002 Update mime type for WAV files

app/conf/annotation_types.conf, app/lib/BaseEditorController.php
PR addresses issue where the "download all" option in the ca_object_representations editor bundle will omit files from the generated downloadable ZIP archive when the file naming policy results in duplicate file name. To resolve this, a system to generate unique file names in this situation is implemented.
=> PROV-3003 Object representation editor bundle "download all" omits files

app/conf/app.conf, app/lib/ConfigurationCheck.php
mediaDirRecursiveExpensiveCheck can be costly on large installations (25000 folders in media), Configuration check then fails on silent timeout.
I have added config to bypass this test (with bypass disabled on default).
=> Add abilityto disable  mediaDirRecursiveExpensiveCheck

app/models/ca_lists.php
PR changes caching behavior for getListCodes() to detect cache drop-outs and regenerate the cache.
=> Fix to allow ca_lists::getListCodes() to tolerate cache drop-outs

app/models/ca_places.php
PR handles issue where ca_places record is inserted without a parent_id by automatically setting the parent_id to the root_id used for the default place hierarchy. This avoids errors in cases where places are created in the user interface outside of a hierarchical context.
=> NOJIRA Set place hierarchy to default when no parent_id is set for place record

app/controllers/editor/objects/ObjectEditorController.php, app/models/ca_places.php
PR prevents false "Could not add parent collection to object" error that may be thrown when saving an object and object-collection hierarchies are enabled even though the object is linked properly the collection and saved.
=> PROV-3012 "Could not add parent collection to object" error thrown when saving object within collection

app/lib/BaseModel.php
When deleting a record with relationships (hierarchical or otherwise) to other records, a warning detailing those relationships is displayed. For hierarchical children, the counts incorrectly include deleted records. PR adds filter for deleted records.
=> PROV-3013 Editor delete "remap" option includes deleted child items in counts

app/conf/app.conf, app/models/ca_lists.php
PR adds configuration option in app.conf to control visibility/availability of selected access_statuses list values in "access" control for a given table/type combinations.
This will allow variations of the access list to be used in different types of records, while still maintaining the access_statuses list as a single definitive source of valid access values.
=> PROV-3009 Add option to omit specific access_statuses values for tables

app/lib/Controller/Request/Session.php
PR improves security (and satisfies current security scanners) by:
- Setting the _httponly_ flag on session cookies to (arguably) mitigate XSS opportunities
- Setting the _secure_ flag on session cookies when https is in use.
=> NOJIRA Set secure and httponly flags on session cookies.

app/conf/app.conf, app/lib/Plugins/PDFRenderer/domPDF.php, app/lib/Plugins/PDFRenderer/wkhtmltopdf.php
PR Implements support for changes implemented on domPDF 0.8.6. 
With domPDF 0.8.6 generation of PDFs that reference external resources such as images and CSS files (basically 99.9% of PDF templates in CA) fail due to newly imposed security restrictions. The PR sets options to allow locally hosted resources to continue to be loaded.
PR also fixes non-functional app.conf use_pdf_renderer option.
=> PROV-3019 Add support for domPDF 0.8.6

app/conf/app.conf, app/controllers/batch/MetadataImportController.php, app/helpers/importHelpers.php, app/helpers/preload.php, app/helpers/utilityHelpers.php, app/lib/ApplicationError.php, app/lib/BaseModel.php, app/lib/Controller/AppController.php, app/lib/Exceptions/UrlFetchException.php, app/lib/MediaUrl.php, app/lib/Plugins/Media/Office.php, app/lib/Plugins/MediaUrl/BaseMediaUrlPlugin.php, app/lib/Plugins/MediaUrl/GoogleDrive.php, app/lib/Plugins/MediaUrl/InternetArchive.php, app/lib/Plugins/MediaUrl/_File.php, app/lib/Plugins/PluginConsumer.php, app/lib/RepresentableBaseModel.php, app/models/ca_object_representations.php, app/models/ca_representation_annotations.php, app/models/ca_set_items.php, app/models/ca_site_pages.php, app/models/ca_user_representation_annotations.php, themes/default/views/bundles/ca_object_representations.php
PR adds facility to allow ingest of media using various types of urls, from standard resource urls to service-specific urls for GoogleDrive, Internet Archive. Is pluggable to simplify expansion in the future to services such as YouTube and Vimeo.
=> PROV-3018 Allow ingest of media representations via service-specific urls

app/lib/Plugins/Media/ImageMagick.php
PR addresses regression that breaks support for media processing using ImageMagick command-line binaries.
=> PROV-3022 Use correct path when attempting to run ImageMagick

app/conf/app.conf, app/conf/media_display.conf, app/conf/media_processing.conf, app/helpers/displayHelpers.php, app/lib/BaseEditorController.php, app/lib/BaseModel.php, app/lib/Media/MediaInfoCoder.php, app/models/ca_object_representations.php
PR adds ability to process uploaded media without retaining the original file. Two new per-version media_processing.conf settings are added:
- SKIP_WHEN_FILE_LARGER_THAN skips processing of a version when the uploaded file is greater than the number of bytes specified here
- REPLACE_WITH_VERSION remaps all calls to the version to another extant version. 
When SKIP_WHEN_FILE_LARGER_THAN is used REPLACE_WITH_VERSION is only honored if the size of the uploaded file exceeds the stated limit. When REPLACE_WITH_VERSION is used without SKIP_WHEN_FILE_LARGER_THAN the version is always skipped and remapped.
=> PROV-2922 Add ability to create a placeholder for object representation record

app/conf/app.conf, app/lib/BaseEditorController.php
PR implements template-based file names for downloaded summary PDFs in the object editor. Previously the download name was a generic name based upon the template used to generate the summary.
=> PROV-2984 Implement configurable summary download names

app/conf/oai_provider.conf, app/lib/Service/OAIPMHService.php
PR adds OAI provider option to use identifiers (Eg. ca_collections.idno) as setSpec values when sets are using relationships or type browse facets. Currently preferred labels and row ids are used. Identifiers are required by some consumers such as EBSCO.
=> PROV-2975 Allow identifiers to be used for setSpecs

app/conf/search_indexing.conf, app/lib/Search/SearchIndexer.php
PR adds ability to filter content to be indexed for search using simple filters on a handful of intrinsic fields: is_preferred, type_id, access and status. The primary use cases is filtering of non-preferred labels for indexing. The addition of type_id allows filtering on specific types of preferred labels. Access and status allow filtering of non-public content in very specific cases (typically you'd want everything indexed and let access control and/or private indexing take care of visibility).
Filters may be set directly on a related table's indexing block, or in the options for a linking table. For related tables, like object labels, filtering configuration is as in this example:
For example, to only index object preferred labels (omitting non-preferred labels) you’d set the …
=> PROV-3006 Add "filters" option to search indexer allowing filtering of indexed content on simple field criteria

app/lib/Attributes/Values/AuthorityAttributeValue.php
PR fixes regression incurred when adding support for authority lookups in advanced search forms. The regression would cause authority lookups to fail in the editor UI.
=> PROV-2989 Fix regression that would cause authority lookups to fail to save in editing UI

app/lib/Utils/CLITools.php, support/bin/caTools
PR removes references to embedded Zend libraries (which are now pulled in via Composer), resolving runtime errors.
=> NOJIRA Fix CLITools errors

app/lib/Controller/RequestDispatcher.php
PR adds support for action-less URLs. When no action is specified the "_default" controller method should be called. This will allow us to make clean(er) URLs for forthcoming Graphql-based services.
=> PROV-3036 Add support for default controller actions

app/lib/BaseModel.php, app/lib/Service/SimpleService.php, app/models/ca_change_log.php
PR extends SimpleService "search" API to take optional log_id and change log mode. When set, the service will only return search matches that have appear in the log with the specified mode(s) after the log_id.
This extension enables creation of simple "changed since the last time" services.
=> PROV-3035 Extend SimpleService to only return records created or modified after a specific change log log_id

app/conf/app.conf, app/helpers/displayHelpers.php, app/helpers/importHelpers.php, app/lib/ApplicationChangeLog.php, app/lib/Browse/BrowseEngine.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/LabelableBaseModelWithAttributes.php, app/lib/Media/MediaViewers/Diva.php, app/lib/Media/MediaViewers/Mirador.php, app/lib/Media/MediaViewers/UniversalViewer.php, app/lib/Plugins/SearchEngine/SqlSearch.php, app/lib/RepresentableBaseModel.php, app/lib/Search/SearchEngine.php, app/models/ca_data_importers.php, app/models/ca_item_comments.php, app/models/ca_object_representations.php, app/models/ca_sets.php, themes/default/views/mediaViewers/DivaManifest.php, themes/default/views/mediaViewers/MiradorManifest.php, themes/default/views/mediaViewers/UniversalViewerManifest.php
PR extends existing blank label text feature to be settable on a per-table basis.
The app.conf "blank_label_text" directive sets default test to use for preferred labels when no text is set.
Currently this single setting is used for all types of records.Additional configuration directives should be added allowing configuration on a per-table basis with fallback to the universal setting. Format of table-specific directives should be <table>_blank_label_text. For example, "ca_objects_blank_label_text"
=> PROV-3038 Make blank_label_text configurable on a per-table basis

app/conf/app.conf, app/helpers/listHelpers.php, app/models/ca_lists.php
PR extends configuration format for app.conf omit_access_statuses directive to allow for additional options, and adds new configuration option to set default value in reconfigured list. This default overrides any set for the overall list, and is useful when the overall list default has bee omitted.
=> PROV-3027 Add configuration option for setting default in list reconfigured with omit_access_statuses

themes/default/views/editor/objects/summary_html.php
PR allows non-media object representation fields to appear in object summaries. Previously, any reference to representation fields were skipped in objet summaries to prevent double output of images. This change is more precisely focussed upon media, but allowed other representation metadata to appear.
=> NOJIRA allow non-media object representation fields to appear in object summaries

app/lib/Import/DataReaders/BaseXMLDataReader.php
PR fixes issue where XPath expressions is XML-based import mappings fail if they include axes such as parent::. The failure is due to incorrect namespacing of these expressions.
=> PROV-3042 Namespace axes properly

app/plugins/prepopulate/conf/prepopulate.conf, app/plugins/prepopulate/prepopulatePlugin.php
PR adds per-rule configuration options to override existing global trigger options. This allows different rules to run on different triggers (Eg edit or save). Previously all rules share the same trigger configuration using the global prepopulate_fields_on_edit or prepopulate_fields_on_save options in prepopulate.conf.
=> PROV-3043 Add per-rule config options

app/models/ca_editor_ui_screens.php
gettext
app/models/ca_editor_ui_screens.php:1203: warning: Empty msgid.  It is reserved by GNU gettext: gettext("") returns the header entry with                                                         meta information, not the empty string.
=> Do not translate empty text

app/lib/BundlableLabelableBaseModelWithAttributes.php
PR addresses several issues relating to detection of duplicate labels:
1. Ignore displayname when comparing entity labels
2. Address issue where entity label comparison on newly created entities would not identify duplicates
3. Improve formatting of error message when dupe is detected but not allowed
=> PROV-3048 Improve detection of duplicate labels

app/models/ca_data_importers.php
PR adds existing record policies supporting merge on existing records, but skipping if no existing record is present. Current policies will always attempt to create a new record when there is no match.
Two policies are added: merge_on_idno_with_skip and merge_on_id_with_skip
=> PROV-3049 Add policies to allow skip if no existing record is present

app/lib/Parsers/TimeExpressionParser.php, themes/default/css/base.css
PR addresses recent regression that would cause dates in month-year delimited format to not parse in some cases.
=> NOJIRA Resolve broken month date expressions

app/models/ca_object_representations.php
PR adds support for history tracking to object representations and inspector current value display for lots, collections and object representations. This allows for "current location" tracking of these record types, which some folks apparently want.
=> NOJIRA add support for object-like tracking with bundles + inspector display on lots, collections and representations

app/lib/Media.php, app/lib/Plugins/Media/Gmagick.php
PR bypasses unnecessary creation of extra previews for non-multipage images and avoids cleanup issues with generated tmp files.
=> NOJIRA Clean up tmp files generated for previews of single page images

app/helpers/utilityHelpers.php, app/lib/ConfigurationExporter.php, install/inc/Installer.php
* Detect default cataloguing locale when running the installer.
* Support restrictToTypes settings for authority attributes in the Installer / profile export
* Previously these were being exported as the ids of the list items.
* Locale codes in the installer are now generated based on the dialect as well if it's set.
* Don't throw warnings if locale settings don't exist for a particular locale but you want to still use it for cataloguing.
=> NOJIRA Fixes for locales and attribute settings in the installer / configuration exporter.

app/lib/Import/DataReaders/ExcelDataReader.php
PR preemptively strips null values in Excel files, when reading for import. These null values can cause problems in general, and will trigger warnings when the content is used as a file path (which happens in the importer). Apparently, PHPExcel reads a backslash followed by a zero as chr(0). 
To avoid warnings this change converts all such values to "/0". This keeps file paths working, but in principle will slightly mangle straight text where literal backslashes are used. Since most (all?) of the time backslashes followed by zeros are part of file paths, this seems like acceptable behavior, but we should reevaluate in the near future.
PR also temporary forces timezone to UTC when reading Excel data to avoid date offset issue, where date column values are read as UTC and forced to server …
=> NOJIRA preemptively strip null values in Excel files; automatically set timezone to UTC to avoid date offset issues

app/lib/Search/SearchResult.php
PR fixes issue when using SearchResult::get() with a .value_id expression (Eg. "ca_objects.my_attribute.value_id") to return the internal value_id value. Currently only value_id for the first found value is returned, even when returnAsArray is set. This change allows a full list of value_ids to be returned.
=> NOJIRA Add support for returning list of attribute value_ids 

app/lib/BaseModel.php
PR Changed change log behavior such that when using RELATED_TABLE change log triggers, changes to metadata attributes are not logged directly to related tables, avoiding overhead and errors
=> NOJIRA When using RELATED_TABLE change log triggers, don't log change to metadata attributes

app/helpers/importHelpers.php
PR convert literal backslashes to forward slashes in splitters so they may be evaluated as file paths. Typical use case is provided import data has MSDOS-style file paths; this modification converts them to something usable in the importer.
=> NOJIRA Convert literal backslashes to forward slashes 

app/conf/external_applications.conf, app/conf/media_processing.conf, app/helpers/mediaPluginHelpers.php, app/lib/Media.php, app/lib/Plugins/Media/Video.php, app/lib/Plugins/MediaUrl/YouTubeDL.php
PR adds support for import of YouTube, Vimeo and Soundcloud content as media representations using the MediaURL framework and the youtube-dl external application (http://ytdl-org.github.io/youtube-dl/)
=> PROV-3018 Add support for YouTube, Vimeo and Soundcloud via youtube-dl

app/helpers/displayHelpers.php, app/helpers/utilityHelpers.php, app/lib/Attributes/Values/CurrencyAttributeValue.php
PR adds per-metadata element option controlling which currency is referred to by the "$" symbol.
=> PROV-3053 Option to configure currency used for "$"

app/models/ca_lists.php, themes/default/css/base.css
PR addresses layout issue in editor when using "list" elements with checklist render mode. Current layout uses CSS max-columns. When used in Chrome and the number of checklist items is less than the maximum number of rows, the layout is incorrectly broken onto two lines.
This PR modifies checklists to use a CSS grid layout, which does not suffer from these problems.
=> PROV-3054 Convert checklist layout to CSS grid to avoid max-columns render errors in Chrome

app/lib/BundlableLabelableBaseModelWithAttributes.php
PR addresses regression that prevents file and media uploads to metadata elements on edit due to incorrect checking of incoming form parameters.
=> NOJIRA Fix regression preventing files from being uploaded on edit to metadata attributes

.gitignore, Vagrantfile.focal, support/scripts/xdebug.ini
Add a new vagrant configuration for Ubuntu Focal, including updates
to external applications, upgrade php to 7.4 and support for xdebug.
It will listen on URL http://localhost:9090 for `providence` and on http://localhost:9999 for `pawtucket2` in case it is also on the local development environment.
It also increases the VCPU and memory, previous setup with 1 CPU and 1024 was too short.
=> Vagrant configuration for Ubuntu Focal

app/conf/access_restrictions.conf, app/conf/search_query_builder.conf, app/conf/user_actions.conf
PR adjusts privileged required for two service API calls:
• Statistics service now requires can_view_system_statistics; previously required can_use_json_simple_service.
• Auth service is now available if user has any service priv. Previously auth was only possible if user had can_use_json_browse_service priv.
=> NOJIRA Adjust priv requirements for statistics

.htaccess, app/conf/app.conf, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/RepresentableBaseModel.php, app/models/ca_object_representations.php, themes/default/css/base.css, themes/default/views/bundles/ca_object_representations.php
PR adds option to allow creation of object representation records without associated media. This may be useful in odd cases where one wishes to create placeholder representation records prior to media ingest.
=> PROV-3058 Support for medialess object representations

app/lib/Parsers/TimeExpressionParser.php, tests/lib/Parsers/TimeExpressionParserTest.php
PR modified display of "before <date>" and "after <date>" expressions such that month-specific expressions (Ex. 1970-03) are displayed with only year and month. Previously the implicit day value would be displayed.
=> PROV-3060 Adjust display behavior of before and after date ranges

app/lib/Attributes/Values/TimeCodeAttributeValue.php
PR resolves issue where Timecode metadata attributes would not honor width and height settings in the editing user interface.
=> PROV-3061 Honor width/height settings

tests/lib/ConfigurationTest.php, tests/lib/data/test.conf
Something is wrong in configuration parsing of conf files, 
i have found it on idno_regexes at search.conf.  
Code  from SearchEngine.php  expects something like 
array(  
'ca_objects' = array(	'[\d]{4}\.[\d]{1,5}\.[\d]{0,5}') 
)
but it gets something like 
array (
0 => 'ca_objects = [[d]{4}\\.[d]{1,5}\\.[d]{0,5}',
)
This PR adds just error reporting, it doesn't include fix.
=> Test idno_regexes

app/lib/Configuration.php, tests/lib/ConfigurationTest.php, tests/lib/data/test.conf
PR addresses issue where escaped backslashes in lists were not honored and updates Configuration caching process for nominally improved performance
=> PR-751 Improper handling of escaped backslashes in config files

assets/jquery/jquery-tileviewer/jquery.tileviewer.js
PR moved zooming slider in viewer outside of controls <div> to allow potential positioning of slider at bottom of viewer
=> NOJIRA move zoom slider outside of control div

app/lib/BundlableLabelableBaseModelWithAttributes.php
PR addresses issue where when adding an entity via a quickadd form, if only display name is set comparison to detect duplicate names will use a null value, usually causing the new name insert to fail.
=> NOJIRA Avoid false positive entity name dupes

app/conf/media_processing.conf, app/lib/Plugins/Media/GD.php, app/lib/Plugins/Media/Gmagick.php, app/lib/Plugins/Media/GraphicsMagick.php, app/lib/Plugins/Media/ImageMagick.php, app/lib/Plugins/Media/Imagick.php
PR implements new "background" media processing property allowing specification of background color for transparent PNG and GIF. Support implemented for all plugins, but only tested for Gmagick, GraphicsMagick and GD. ImageMagick support is likely to work as options for GraphicsMagick and ImageMagick are similar. No idea if the Imagick patch will work. Buginess in the Gmagick API means we have to jump through some very specific hoops to get transparency to work. For Imagick the code takes a API at its word. 
Will set up and test with Imagick/Imagemagick as time allows. Would appreciate if someone running IM might take the time to evaluate and return feedback.
=> PROV-3056 PNGs with a transparent background render jpg preview with black background

app/lib/BatchProcessor.php, app/lib/Plugins/TaskQueueHandlers/metadataImport.php, app/lib/Search/SearchIndexer.php, app/models/ca_data_importers.php, themes/default/views/mailTemplates/batch_metadata_import_completed.tpl
PR adds template to support email notifications for metadata imports, and disabled search index queuing when importing in the background. Disabling queuing prevents generation of large indexing backlogs by an import.
=> PROV-3065 Enable background metadata imports

app/conf/media_display.conf, app/conf/media_processing.conf, app/lib/Media/BaseMediaViewer.php, app/lib/Plugins/Media/PDFWand.php, themes/default/views/mediaViewers/pdfjs.php
PR adds "compress" property to PDFWand media processing plugin. The property exposes Ghostscript's dPDFSETTINGS option, which provides five presets for control of PDF file size (and quality). Changes include:
- Add property to support dPDFSETTINGS when processing PDFs
- Add "compressed" PDF version to standard media_process.conf file using "screen" PDF size/quality settings. This provides smallest file at reasonable quality (YMMV).
- Modify pdfjs media viewer to use versions other than original pdf.
- Modify standard media_display.conf file to use compressed version when displaying PDFs.
=> PROV-3066 Implement compressed PDF support

app/lib/Plugins/Media/Gmagick.php
PR fixes incorrect counting of image previews that could result in an infinite loop, stalling media processing.
=> NOJIRA properly count previews, avoiding potentially infinite loop

app/helpers/accessHelpers.php
PR extends caMakeTypeIDList() helper to use subject table type_ids when a label table is passed. This allows the "types" parameter in search indexing (which is used to restrict indexing of related records to specific types) to be used for labels as well as the primary record type.
=> NOJIRA allow type_id lists to be generated for label types using subject record types;

app/lib/Browse/BrowseEngine.php
PR fixes issue where fieldList facets for "access" and "status" fields would refuse to browse on zero values.
=> NOJIRA allow "0" value for access and status fieldList browses

app/controllers/batch/MediaImportController.php, app/lib/BatchProcessor.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/Utils/CLIUtils/ImportExport.php, app/models/ca_object_representations.php, themes/default/views/batch/mediaimport/import_options_html.php
PR add remove-existing-media option to batch media importer, facilitating in-place replacement of media; and  moves embedded metadata mapping data extraction to the representation model to ensure it is performed during metadata imports via the objectRepresentation splitter.
=> PROV-3067, PROV-2781  add remove-existing-media option to batch media importer; expand metdata extraction to metadata importer

app/lib/BaseFindController.php
PR checks validity to type restriction, to avoid "poisoning" of the session var controlling type restrictions.
=> PROV-3070 Type-restricted finds initiated by menu option "lose" restrictions 

app/helpers/importHelpers.php, app/lib/LabelableBaseModelWithAttributes.php, app/models/ca_data_importers.php, app/models/ca_entity_labels.php
When matching entity preferred labels, current behavior is to match all elements of the name (forename, surname, middlename, etc). This should be expanded such that displayname is checked first, then forename/surname (without other elements), with options for full matching.
PR implement first element of required changes:
- Try matching display name first in splitters
- Apply skipIfEmpty and skipIfExpression options when determining preferred label mapping to use for matching (in cases where there are multiple conditional mappings)
-Pass through importer options to entity label setter, to allow for application of doNotParse option
=> PROV-3072 Improve entity preferred label matching in importer

app/lib/HistoryTrackingCurrentValueTrait.php
PR modifies behavior of history tracking getHistory() call to include undated entries at the end of the returned chronology. Previously, undated entries were omitted.
=> PROV-3068 Include date-less entries

app/lib/Attributes/Values/CurrencyAttributeValue.php
PR properly sets currency for dollar-sign denominated values when run from command-line. Previously USD would be used no matter what the default was set to.
=> PROV-3053 Set default dollar currency properly when used in command-line environment

app/lib/BaseSettings.php, themes/default/views/bundles/ca_object_representations_classic.php
PR resolves missing "editable elements" configuration list in representation bundle config; eliminates warning in classic representation bundle due to incorrect call to sort control helper.
=> PROV-2827 Fix settings regression and sort warning

app/models/ca_bundle_displays.php
PR re-establishes maximumLength option for bundle display placements, with provision for dealing with HTML in truncated text. The option had been disabled because it would trash pages when truncating HTML text, creating un-closed tags.
=> PROV-3069 Re-establish maximumLength option for bundle displays

app/lib/Import/DataReaders/ExcelDataReader.php
PR temporarily sets timezone to UTC during reading of Excel files for import to avoid skew of date/times from UTC to local timezone.
=> PROV-1037 Adjust timezone to UTC while processing Excel files to avoid date/time skew

app/lib/Utils/DataMigrationUtils.php, app/models/ca_data_importers.php
PR makes additional changes to entity preferred labels matching:
1. Add skipIfEmpty/skipIfExpression support in entity label matching
2. Omit middlename in DataMigrationUtils::getEntityID()
=> PROV-3072 Preliminary changes to matching

app/lib/Logging/Eventlog.php
PR filters event log content through HTML Purifier, as log content may in some cases include URL logs that contain unsafe content.
=> NOJIRA Run event log content through Purifier as logs may contain unsafe content

app/lib/BaseModelWithAttributes.php, app/models/ca_data_importers.php
PR adds data importer improvements:
- Adds skipDuplicateValues mapping option to suppress duplicate import values across entire mapping
- Adds support for evaluation of skipIfEmpty and skipIfExpression options when determining which preferred label mapping to use for existingRecordPolicy evaluation. Previously the first found mapping would be used, regardless of options set.
- Avoids warnings when skipIfValue value is non-scalar.
=> Data importer improvements

app/conf/authentication.conf, app/lib/Auth/Adapters/Shibboleth.php
PR resolves issues caused by incorrect code merge on Shibboleth auth adapter, including incorrect auth return value (would return negative auth in many cases, even if credentials were correct); and clarifies attribute mapping.
=> NOJIRA Fix broken Shibboleth/SAML adapter

app/controllers/manage/SetController.php, themes/default/views/manage/set_list_by_user_html.php
Set list by user is a nested iteration, as it iterates over users, and for each user over the user's sets. The code sort of mixes both iterations, the pagination seems to happen only on users, instead of on sets or on users and sets. The shoehorning of both iterations into presentation  code meant for one results in the wrong heading being shown. This hack does not address the pagination issue, it just postpones setting the 'user' label into type_name_* for pagination purposes until after these variables have produced the right heading for the real set type. At least users are slightly less confused...
=> Quick fix for Set list by user headings

app/helpers/utilityHelpers.php
using brackets doesn't work for PHP 8, throws deprecation warning in PHP 7.4
=> use [] instead of {} for getting character

app/conf/authentication.conf, app/lib/Auth/AuthenticationManager.php
PR adds option to external auth that marks specific controllers a "free" and not requiring authentication. Primarily useful in Pawtucket for set up of public (not authenticated) areas.
=> NOJIRA add option to mark "free" controllers that do not require authentication

app/conf/assets.conf
PR corrects capitalization on name of doT.js library. Incorrect capitalization causes issues on Linux (but not MacOS).
=> PROV-1798 Fix capitialization of Javascript lib

app/conf/app.conf
Localize the default text in required_field_marker, for instances where show_required_field_marker is set to 1.
The text to be translated would not be picked up if maintained verbatim  (that is, _t((Required)) would not be localized at runtime for some reason tied to the use of parenthesis). Not knowing the escape rules (if any), I've cowardly moved the string to square brackets, with _t([Required]) working as expected. Installs using the default string will notice a change from (Required) to [Required]. Hope it helps anyway.
=> Localize required_field_marker

app/plugins/prepopulate/prepopulatePlugin.php
Previous fix didn't actually allow the commends to run, but did make them available in the command listing.
=> NOJIRA Prevent prepopulate plugin from clobbering other caUtils plugin commands - further fix.

app/models/ca_entities.php
PR implements behavior to addLabel/editLabel/replaceLabel() methods for entities to auto-split entity label displayname into constituent elements (first name, last name, etc)  when only a displayname is passed.
=> NOJIRA Split entity displaynames into constituent elements when only display name is passed

app/lib/RepresentableBaseModel.php
PR extends RepresentableBaseModel::findRepresentations() to return all related representations when no mimetype or mimetype regex is passed.
=> NOJIRA allow findRepresentations() to return reps when no mimetype is provided

app/lib/RepresentableBaseModel.php
PR extends RepresentableBaseModel::findRepresentations() to return all related representations when no mimetype or mimetype regex is passed.
=> NOJIRA allow findRepresentations() to return reps when no mimetype is passed

app/lib/Plugins/SearchEngine/ElasticSearch/Mapping.php
* Use a dynamic template to always store these as integers so that we don't get exceptions when indexing records for this data type.
When sending the data to ES without this _depending how much / what type of data is in the system_ this can end with a Fatal error:
```
PHP Fatal error:  Uncaught ApplicationException: Indexing error [illegal_argument_exception]: mapper [ca_object_labels/name_content_ids] cannot be changed from type [text] to [keyword] in /var/www/html/providence/app/lib/Plugins/SearchEngine/ElasticSearch.php:671
Stack trace:
#0 /var/www/html/providence/app/lib/Plugins/SearchEngine/ElasticSearch.php(497): WLPlugSearchEngineElasticSearch->flushContentBuffer()
#1 /var/www/html/providence/app/lib/Search/SearchIndexer.php(1128): …
```
=> NOJIRA Fix indexing type for _content_ids fields.

themes/default/views/administrate/setup/Results/ca_list_items_results_list_html.php, themes/default/views/administrate/setup/Results/ca_relationship_types_list_html.php
When using the default display in the Lists & Vocabularies editor or Relationship Type editor, all display values are blank. This PR ensures appropriate default bundle specs are used for these two views.
=> PROV-3084 Make sure default bundles are used

assets/ca/ca.directorybrowser.js, themes/default/views/batch/mediaimport/import_options_html.php
PR implements ability to click on non-directories to deselect current directory, implicitly selecting root of directory hierarchy for import. Previously it was not possible to select the root directory once a sub-directory had been selected.
=> PROV-3085 Allow selection of root directory in media importer directory browser

app/lib/Plugins/SearchEngine/ElasticSearch.php
I did some profiling against the ItemService API and found that \ElasticSearch\Mapping::prefetchElementInfo was getting called a lot:
https://blackfire.io/profiles/9c0111fb-4a4f-4b2f-ac6e-4e0e4e6f637d/graph
This reuses a static mapping rather than newing one up a number of times during the request.
=> Optimise calculation of whether a mapping needs a refresh by using a single instance of the CA mapping.

app/conf/search.conf, app/lib/Configuration.php, tests/lib/ConfigurationTest.php, tests/lib/data/test.conf
For scalar configuration entries (standalone key-values) backslash escaped characters are not processed. This results in inconsistent behavior where backslashes are returned as-is. Need to process backslashes in scalars such that \<char> returns \<char> and <char> returns \<char>. PR changes parsing of scalar values to handle backslash escaping similarly to that done for list and associative values.
=> PROV-3087 Backslash escapes in scalars in configuration aren't processed as in other entries

app/lib/BaseModel.php, app/lib/LabelableBaseModelWithAttributes.php
PR improves performance of *Model::find() by only pulling primary key from database when possible (which happens to be most of the time).
=> NOJIRA Improve performance of *Model::find() 

app/lib/Auth/AuthenticationManager.php
PR prevents warnings when authentication.conf file lacks `auth_not_required_for_controllers` setting.
=> NOJIRA Check for existence

app/helpers/utilityHelpers.php, app/lib/Attributes/Values/CurrencyAttributeValue.php, tests/lib/AttributeValues/CurrencyAttributeValueTest.php
PR fixes regression where currency values with commas would be truncated at the comma. Also adds tests for currency value parsing.
=> NOJIRA Fix regression where currency values with commas are truncated

app/helpers/displayHelpers.php
PR add check to disk display "Undefined" EXIF chunks to avoid including invalid characters in display data that trigger Javascript errors. These chunks usually contain proprietary data that is not usefully displayable.
=> NOJIRA avoid errors due to invalid EXIF data by skipping unlabeled chunks

app/lib/BaseModel.php, app/lib/Parsers/TilepicParser.php, app/lib/Plugins/Media/Gmagick.php, app/lib/Plugins/Media/GraphicsMagick.php, app/lib/Plugins/Media/ImageMagick.php, app/lib/Plugins/Media/Imagick.php
PR implements changes to avoid unnecessary colorspace changes which were causing color shifts in installations of ImageMagick without color management installed.
=> PROV-2287 Avoid imagick/imagemagick color shifts

install/inc/Installer.php, install/profiles/xml/base.xml
The installer parses each installed profile in full in order to extract the name, description, status and locales. This is slow and unnecessary as the required information is always at the top of the file. For installations with many profiles, installer loading time is often > 10 seconds. 
This PR modifies profile information extraction to use a streaming XML parser that only reads profiles to the extent necessary and then bails. This results in much faster loading types - under 1 second in all cases tested so far.
PR also includes minor changes to base profile (base.xml) suggested by users.
=> PROV-3089 Replace full profile load with XMLReader() streaming parser

tests/testsWithData/queries/TimestampSearchQueryTest.php
PR updates timestamp query test to use interval containing current year.
=> NOJIRA update test to use current year interval

app/helpers/htmlFormHelpers.php, app/lib/Attributes/Values/GeocodeAttributeValue.php, app/lib/Plugins/GeographicMap/Leaflet.php
PR adds options to geocode metadata elements to control minimum and maximum allowable zoom, default zoom, and default location for newly opened maps.
=> PROV-3090 Add options to control min/max/default zoom and default location for new maps

app/lib/Search/SearchIndexer.php
PR puts cache in front of getIndexedTables() to nominally improve performance.
=> NOJIRA Cache data from getIndexedTables() to improve performance

app/helpers/utilityHelpers.php, app/lib/Utils/CLIUtils/Maintenance.php, app/models/ca_object_representations.php
PR prevents multifile preview media from being incorrectly deleted by caUtils remove-unused-media command.
=> PROV-3092 Include multifile preview paths in "used" list

app/controllers/lookup/ObjectCollectionHierarchyController.php, app/lib/BundlableLabelableBaseModelWithAttributes.php
PR mitigates two bottlenecks that can cause very slow performance when viewing hierarchies with large numbers of records in single hierarchy levels.
=> NOJIRA Modifications to improve performance with hierarchies containing a very large number of items in a single level

app/lib/Attributes/Values/AttributeValue.php, app/lib/Parsers/ExpressionParser.php
PR adds two suggestions for Tac:
1. value_id attribute should be protected in attribute base class to allow access from subclasses
2. HOA class name is incorrect (oddly both the incorrect and "correct" versions work without error)
=> Fix minor code issues found in static analysis

app/lib/Plugins/SearchEngine/SqlSearch2.php
PR changes stemming criteria to require ascii letter rather than unicode letter class, which throws errors in PHP 7.2 and on systems built against older PCRE libraries. Since stemming is english-specific, requiring an ascii character to initiate stemming seems reasonable.
=> PROV-1798 Don't use unsupported character class – throws errors in PHP 7.2

app/lib/Utils/DataMigrationUtils.php, app/refineries/collectionHierarchyBuilder/collectionHierarchyBuilderRefinery.php, app/refineries/collectionIndentedHierarchyBuilder/collectionIndentedHierarchyBuilderRefinery.php, app/refineries/entityHierarchyBuilder/entityHierarchyBuilderRefinery.php, app/refineries/listItemHierarchyBuilder/listItemHierarchyBuilderRefinery.php, app/refineries/listItemIndentedHierarchyBuilder/listItemIndentedHierarchyBuilderRefinery.php, app/refineries/objectHierarchyBuilder/objectHierarchyBuilderRefinery.php, app/refineries/occurrenceHierarchyBuilder/occurrenceHierarchyBuilderRefinery.php, app/refineries/placeHierarchyBuilder/placeHierarchyBuilderRefinery.php, app/refineries/storageLocationHierarchyBuilder/storageLocationHierarchyBuilderRefinery.php, install/inc/schema_mysql.sql
PR adds to data importer two record matching modifiers that are currently only available in splitter refineries, ignoreType and ignoreParent. These would be useful for hierarchy builders as well, when parents to be matched may include items imported by the primary mapping.
=> PROV-3093 Add ignoreType and ignoreParent refinery options to hierarchy builder refineries

app/models/ca_data_importers.php
PR resolves issue where existing record checks in the importer were not being honored when importing list items due to incorrect injection of list context. The item_id of the list_id mapping was being injected, rather than the actual numeric list_id.
=> PROV-3094 Fix broken existing record policy checks for ca_list_items due

app/lib/Plugins/Media/PDFWand.php
PR changes PDF processing behavior to use standard uploaded PDF as "compressed" version when compression fails. The previous behavior threw an error when Ghostscript compression failed and effectively made some PDFs un-uploadable.
=> PROV-3066 Use standard PDF when compression fails

app/lib/Parsers/TimeExpressionParser/es_ES.lang, app/lib/Parsers/TimeExpressionParser/es_MX.lang
PR corrects incorrect month translation tables in es_ES and es_MX translations for date/time parser.
=> PROV-3095 Correct month translations in Spanish date/time parser localization

app/helpers/printHelpers.php, app/lib/Plugins/PDFRenderer/wkhtmltopdf.php, app/lib/Print/PDFRenderer.php
* Enable wkhtmltopdf support for custom page size and print media queries.
* use --page-height and --page-width for custom page size
* Use --page-size for standard page size
* Fix calculation of points when initial measurement is in mm (25.4 mm in an inch).
* More precision when calculating metric lengths from point.
This is specified as follows:
```
* @pageSize Custom(89mm,28.5mm)
```
=> Add support for `Custom` paper size when printing.

themes/default/views/bundles/hierarchy_location.php
PR addresses issue where the Location in Hierarchy (`hierarchy_location`) bundle appears broken when strict type checking is enabled for collections and object-collection hierarchies are enabled. Issue is due to improper hiding of "add object" pane while "add object" table is correct suppressed.
=> PROV-3097 Broken hierarchy location bundle when strict type checking is enabled

app/lib/BaseModel.php
PR fixes incorrect access values checking in getIdnoForID(). Note that since access values are not used in Providence this doesn't actually affect Providence, but we want this code to mirror that used in Pawtucket.
=> NOJIRA Fix for incorrect access checking in getIdnoForID() 

app/lib/Plugins/SearchEngine/SqlSearch2.php
PR corrects stemming code to ensure stemmed term is compared against stemmed index term rather than index word.
=> PROV-1798 Compare stemmed term to index stem rather than index word

app/lib/Plugins/Media/Gmagick.php
PR prevents null calls to gmagick rotation, which cause errors on some systems (and are never needed in any event).
=> NOJIRA calling rotate() with null value causes errors on some systems

app/lib/Import/DataReaders/FMPXMLResultReader.php
PR modified FileMakerPro XML import data reader to return values in repeating structure, as implied by reader settings. Without this change the reader is broken in most scenarios.
=> NOJIRA return values in repeating structure as required.

app/helpers/displayHelpers.php, app/lib/BaseEditorController.php, app/lib/HistoryTrackingCurrentValueTrait.php, assets/ca/ca.bundleupdate.js, themes/default/views/bundles/history_tracking_chronology.php
PR modifies return to home location endpoint  to only consider items currently in location, not all. This saves time and provides accurate counts of records modified; fix bundle update mechanism to provide for update of current content list after return to home has run.
=> PROV-2793 Refactor return to home location endpoint

app/conf/search_query_builder.conf
PR adds search builder configuration for three tables that may benefit from builder functionality: movements, object representations and list items.
=> PROV-1798 Add config for movements, object representations and list items

app/conf/user_pref_defs.conf, app/lib/BundlableLabelableBaseModelWithAttributes.php
PR addresses inability to include duplicated records in related sets when using the editor "duplicate record" tool.
=> PROV-3102 Support inclusion of duplicated item in related sets via the record duplication tool

app/helpers/initializeLocale.php
PR ensures real path (no symlinks) are used when loading locale files, due to an apparent limitation of Zend_Locale.
=> NOJIRA Ensure real path is used

app/lib/MetadataAlerts/TriggerTypes/Modification.php
This PR further fixes an issue where modification metadata alerts don't get triggered for attributes inside a container.
=> PROV-3101 Trigger filters on child attributes inside a container.

app/lib/Parsers/TimeExpressionParser.php, tests/lib/Parsers/TimeExpressionParserTest.php
PR resolves issue where ISO dates on interval boundaries would display as ranges.
=> PROV-3104 Display ISO dates on boundary intervals properly

app/conf/app.conf, app/lib/Plugins/Media/Gmagick.php
Multipage TIFF files are processed as multipage documents with previews for each image in the file. Some software packages (possibly Silverfast) appear to create TIFFs that have the image duplicated across several "pages". This PR adds an app.conf option to skip multipage processing for TIFFs across the board in these cases. The default remains to process all data present in the TIFF file.
=> PROV-3105 Add option to skip processing of additional pages in multi-page TIFF media

app/lib/BaseModel.php, app/lib/LabelableBaseModelWithAttributes.php
PR escapes sort fields in BaseModel::find() to avoid errors in MySQL8 when "rank" field name is used.
=> PROV-2788 Escape sort field (which may be "rank")

app/controllers/administrate/setup/ConfigurationCheckController.php, app/helpers/mediaPluginHelpers.php
Media helper functions that return paths to external applications cache values (good), but offer no way to force those values to update short of clearing the entire application cache (bad). This PR adds an option to force reloading of these values. 
Forced reloading of cached external application paths can be triggered by passing a "noCache" option to each external application path helper, or by defining the __CA_DONT_CACHE_EXTERNAL_APPLICATION_PATHS__ constant to true.
The system configuration check web UI now sets this constant, forcing update of these paths each time a configuration check is performed.
=> PROV-3106 Add helper options and constant to enable force reloading of external application path values

app/helpers/searchHelpers.php, themes/default/css/base.css
PR sets upper limit on width of relationship bundle sort drop-downs, preventing odd formatting when user has very long field names. Also now clear cache and update sort menu when element names change (rather than wait for the cache to expire).
=> NOJIRA Set upper limit for width of sort drop-down

app/helpers/mediaPluginHelpers.php
PR resolves issue where path for dcraw external application was incorrectly cached. This would cause calls to dcraw are the initial one to fail.
=> NOJIRA Cache path, not return code

app/helpers/utilityHelpers.php, app/lib/BaseLabel.php, app/models/ca_collection_labels.php, app/models/ca_loan_labels.php, app/models/ca_movement_labels.php, app/models/ca_object_labels.php, app/models/ca_object_lot_labels.php, app/models/ca_object_representation_labels.php, app/models/ca_occurrence_labels.php, app/models/ca_tour_stop_labels.php, app/version.php, install/inc/schema_mysql.sql, support/sql/migrations/169.sql
PR extends maximum possible preferred/non-preferred labels length to 16384 characters for these tables:
- ca_collections
- ca_occurrences
- ca_object_lots
- ca_objects
- ca_tour_stops
- ca_loansca_movements
- ca_object_representations
=> PROV-3109 Extend label length

support/sql/migrations/169.sql
PR modifies schema update to avoid truncation issues when name_sort contains > 255 characters in existing db.
=> PROV-3109 Trim name_sort before resizing to avoid truncation errors

app/lib/BaseModel.php, app/lib/Error/errors.en_us, app/lib/RepresentableBaseModel.php, app/models/ca_object_representations.php
When media files are correctly placed but unreadable by the application (usually due to file permissions or SELinux) user PHP warnings are sprayed about and misleading errors stating that the media already exists in the database. The PR catches unreadable media files and prevents warnings. Errors are now emitted by addRepresentation() and editRepresentation().
=> PROV-3110 Be sensible in the face of restrictive file permissions on media

app/lib/Utils/CLIUtils/Media.php
PR adds option to caUtils reprocess-media command to detect and reprocess any media that are awaiting queue processing. This is useful for forcing processing of media where queue processing has failed for some reason.
=> PROV-3112 Add "unprocessed" option

app/lib/Browse/BrowseEngine.php
PR fixes SQL error when getting facet contents for "relationship_types" facets due to incorrect query syntax.
=> PROV-3113 Fix SQL error in relationship types browse

app/helpers/accessHelpers.php
PR changes access behavior to consider all logged in users "privileged" as if they were coming from a privileged IP address. This is only used in Pawtucket and merged here for consistency.
=> NOJIRA make logged in users "privileged"

app/lib/RepresentableBaseModel.php
PR restored ca_object_representations-based editing of representation metadata, which had been broken by added checks for existence of media in RepresentableBaseModel::editRepresentation().
=> NOJIRA allow unspecified media in editRepresentation()

app/conf/app.conf, app/conf/search.conf, app/lib/Plugins/SearchEngine/SqlSearch2.php, app/lib/Search/SearchIndexer.php
The search indexer can mark index entries as restricted and not for use by Pawtucket for public search. Currently, this must be explicitly configured in search_indexing.conf, with the typical use case making related entities with specific relationship types unsearchable (Eg donor names).
PR modifies the indexer to set privacy of related indexing according to the related record's "access" field value in the absence of specific search_index.conf configuration. Thus, an entity with no public access will now automatically be indexed as private. Previously, it would be public by default.
=> PROV-3117 Indexer now sets index entry privacy subject to related record access

app/controllers/system/ErrorController.php, app/helpers/utilityHelpers.php, app/lib/AppNavigation.php, app/lib/Cache/ExternalCache.php, app/lib/Cache/JSONEncoder.php, app/lib/Controller/AppController.php, app/lib/Controller/Request/Session.php, app/lib/Exceptions/ExternalCacheInvalidParameterException.php, app/lib/GarbageCollection.php, app/lib/Utils/CLIUtils/Maintenance.php, index.php
PR implements fixes for various issues/problems/shortcomings in  the current Stash-based application data caching system:
1. When using the file-based cache race conditions can cause individual cache files to be corrupted. Since the cache files contain executable PHP code, subsequent loading causes fatal syntax errors. There is no Stash-provided fix for this issue. The PR includes a new JSON-based cache serializer.
2. When using the file-based cache abrupt loss of session can occur due to race conditions. The PR includes changes to prevent session data from being inadvertently overwritten when a routing error occurs.
3. Garbage collection of the cache is partially broken, resulting in cache overflows and when using the file-based cache periodic high-CPU load and unresponsiveness. GC has …
=> PROV-3116 Caching improvements

app/lib/BaseFindController.php, app/models/ca_editor_uis.php, app/models/ca_object_representations.php
PR resolves a grab bag of warnings:
- Avoid warning when annotation pull on a representation returns nothing
- Avoid warning in editor UI code when no type-specific definitions are available
- Remove old barcode cleanup code
=> Miscellaneous cleanup

app/controllers/lookup/ObjectCollectionHierarchyController.php
In some situations the hierarchy browser will fail to show all objects and collections in a hierarchy level due to optimizations intended to limit the quantity of data pulled. The incidence and scope of the problem depends upon the record and relationship types of the data in the level and how the system is configured. PR resolves the issue by pulling additional data where needed.
=> PROV-3120 Ensure all hierarchy level items are displayed

app/conf/annotation_types.conf, app/helpers/avHelpers.php
PR enables annotations for MTS format video and adds checks to avoid mis-classifying MP4 AVC files as MTS.
=> PROV-3107 Allow annotations for MTS files

themes/default/views/bundles/hierarchy_location.php
PR resolves issue where forms that include the "Location in hierarchy" bundle (hierarchy_location) for records that allow ad-hoc hierarchies (such as ca_objects, ca_collections, ca_entities) throw javascript errors in batch editing mode, disabling the entire form in some browsers.
=> PROV-3121 "Location in hierarchy" bundle throws javascript errors when present batch editing form on some records

install/inc/Installer.php, install/inc/page2.php
PR addresses issue where preinstall tasks are run any time the installer page is loaded. The is unnecessary but benign, unless ElasticSearch indexing is used, in which case the preinstall task handler will truncate the ES index before evaluating whether the install is actually allowed.
This PR makes preinstall tasks contingent on evaluation of installation validity and adds checks in a couple of other places for good measure.
=> PROV-3122 Don't truncte ElasticSearch index when installer page in loaded unless install is actually going to happen

app/lib/Search/SearchIndexer.php, app/lib/Search/SearchResult.php
PR adds additional option to SearchResult::get() for trimming of hierarchy levels (Eg. don't return lowest X levels), which is useful in display templates; minor change to search indexer to avoid warnings in some situations.
=> NOJIRA Add additional option to trim hierarchy levels in SearchResult::get()

app/lib/BaseLabel.php, app/models/ca_entity_labels.php
PR changes generated sortable value for entities to be "surname, forename" rather than based upon the display name using title heuristics.
=> PROV-3126 Make sortable entity names surname, forename based

app/lib/BaseFindController.php, app/models/ca_bundle_displays.php
PR changes method by which sort field refs for containers in search results are generated to improve results. It will now to sort on the first field referenced in a display template rather than try to sort on a numeric field, and if that fails guess. If no template is defined it will fall back to the old behavior.
PR also attempts to improve search result display performance by eliminating count data in returned set lists and caching display lists.
=> NOJIRA changes to improve sorting on containers in search results, and generally improve display performance

app/lib/LabelableBaseModelWithAttributes.php
PR corrects incorrect quoting of sort fields in find() method. Issue was introduced by code quoting fields for compatibility with MySQL 8.
=> PROV-2788 Fix quoting of sort fields in find()

app/controllers/batch/EditorController.php
PR changes batch editor behavior to infer use of set if provided identifier is numeric. This allows existing "batch-edit-from-results-screen" option to function without modification.
=> PROV-3118 Infer set target for numeric values

app/lib/BundlableLabelableBaseModelWithAttributes.php, app/models/ca_object_representations.php, themes/default/views/bundles/ca_object_representations.php
PR resolves several issues in the object representation bundle:
1. Remove regression preventing all media upload in "classic" version of object representation bundle (some users are still using this interface)
2. When checking for existing media with the same MD5 checksum, filter deleted media
3. Honor editable bundle sort setting for all fields in "new" object representation bundle interface
=> PROV-3098 Resolve issues in object representation bundle

app/lib/Plugins/SearchEngine/ElasticSearch.php
After transition to ElasticSearch before  full  reindexing 
by running ./support/bin/caUtils  purge-deleted    to remove stale records, i am getting 
lot of  errors:
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/providence/app/lib/Plugins/SearchEngine/ElasticSearch.php on line 626
=> Validate existence of parameter

app/conf/access_restrictions.conf
PR makes possession of any json service priv enough for access to the auth endpoint. Currently user must have access to all services to be able to login, which doesn't make sense.
=> NOJIRA Make any service membership enough for auth action

app/lib/Search/SearchBase.php
PR resolves potential indexing issue with systems where a metadata element is defined with a code identical to an intrinsic. The metadata element will be pulled for indexing, even if it isn't bound to the record being indexed. PR introduces a check to use intrinsic when present.
=> NOJIRA Add check to prevent attempted indexing of metadata elements with codes that match intrinsic names

app/controllers/batch/MediaImportController.php, app/lib/BatchProcessor.php, themes/default/views/batch/mediaimport/import_options_html.php
PR adds options to control labels on newly created target records in media importer. Options include:
1. Set label to identifier
2. Set label to user-entered text
3. Set label to file name
4. Set label to file name without extension
5. Set label to directory + file name
6. Set label to "blank" value (as configured)
=> PROV-3131 Add media importer options controlling format and content of labels on newly created target records

themes/default/views/find/Search/search_sets_html.php
* Previously the set id parameter passed didn't match the url pattern
used in 1b30f3d5ba37489f95c8331d294ef43a6739aae9
* Fixes an issue where if you click onto a different screen other than
the default screen in the batch edit UI you get an
ApplicationException::('Invalid target')
=> NOJIRA Fix set batch editing when opening set from search results.

app/conf/search_indexing.conf
The stock search_indexing.conf file indexes parent_id for ca_objects only. PR indexes parent_id on other common hierarchical tables, including ca_places, ca_collections, ca_occurrences, ca_list_items and ca_storage_locations.
=> Resolves #955 - add parent_id entries

app/lib/BaseSearchController.php
When broken out by type, "find" menu entries do not follow the declared type list sort order. The same list in the "new" menu do honor the specified sort. PR changes menu code to use list functions to grab types rather than generic hierarchy functions, which gets us correct sorting without extra work.
=> Resolves #958 Type-specific entries in "find" menu don't honor list sort order

app/helpers/displayHelpers.php
PR added "NL2BR" template placeholder modifier that runs PHP nl2br() function on tag value prior to output. This provides a convenient way to ensure text line breaks display in HTML output from within the display template or import mapping template.
=> Add NL2BR modifier to convert line breaks to HTML

app/models/ca_data_importer_items.php, app/models/ca_data_importers.php
PR adds three new import mapping options to transform case of imported text values: toUpperCase, toLowerCase and upperCaseFirst
=> Add importer mapping options to force text case

app/conf/app.conf
PR resolves issue where displays used in summaries linked to related records point to the record being viewed when the placement does not define an output template. This due to the default templates defined in app.conf lacking explicit units to force resolution of links relative to the related record.
Reported by Peter B: https://collectiveaccess.org/support/index.php?p=/discussion/comment/323733#Comment_323733
=> Resolves #966 declare explicit units in default display templates

app/helpers/searchHelpers.php, app/lib/BundlableLabelableBaseModelWithAttributes.php
When <table>_show_related_counts_in_inspector_for option is set, related record counts do not match the number of records returned when the linked search is executed when. related records have multiple relationships. This is due to the returned count being number of relationships rather than number of related items.
PR corrects potentially incorrect related record counts due to multiple relationships between edited record and related record by changing returned count to that for unique related records.
=> PR Fix incorrect editor inspector related record counts  

app/lib/Parsers/ExpressionParser/ExpressionGrammar.pp
The expression parser will throw a parse error when > 2 expressions are strung together with boolean OR's. Eg:
`(length(^/locfield1) > 0) OR (length(^/locfield2) > 0) OR (length(^/locfield3) > 0) OR (length(^/locfield4) > 0)`
PR extends the expression grammar to resolve this.
=> Resolves #977 Allow OR's between multiple expressions

themes/default/views/bundles/ca_object_lots.php
PR suppresses unnecessary sorting controls in ca_object_lots editing bundle when shown in the object editor, which only one lot will ever be shown.
=> Resolves #979

app/models/ca_metadata_alert_triggers.php, themes/default/views/manage/metadata_alert_rules/ajax_rule_trigger_filter_form_html.php
* Line break between alert filters rather than a semicolon
* PHPDoc for ca_metadata_alert_triggers::fireTrigger
=> Tweaks to metadata alerts

app/lib/Plugins/SearchEngine/SqlSearch2.php, assets/ca/ca.querytranslator.js
PR address various reported query builder issues:
1. Resolve errors triggered when searching on numeric fields
2. Ensure top-level boolean setting is honored
3. Parse contains, begins with and ends with mode searches properly
4. Improve performance of "contains" searches
=> Resolve various query builder issues

app/lib/BundlableLabelableBaseModelWithAttributes.php
PR makes default behavior to valid idno for all records. Previously validation for root records in hierarchies was bypassed. Bypassing validation for hierarchy root records in now optional. 
This behavior is preferrable in general, and important for the forthcoming GraphQL services layer.
=> Make default to validate idno in all cases

app/lib/BaseModel.php, app/lib/RepresentableBaseModel.php
PR makes the following changes to models:
1. Controls for how addRelationship() and friends process related ids. Previously they were always resolved against row_ids (if numeric) and then as idnos (if no previous match found). New options allow one or the other match to be disabled.
2. Make length validation checks multi-byte aware. Had been using old single byte character length functions.
3. Add type functions needed by GraphQL services layer
4. Include URL list in returned representation list, for consistency with other calls
=> Miscellaneous model options, required for forthcoming GraphQL services layer (and useful in general)

app/lib/HistoryTrackingCurrentValueTrait.php
* Get label for placements from the default UI for relationships
- Bundles for screens now take the pattern of ca_tablename.bundle
=> Get attribute values for non-type restricted relationships eg storage

app/lib/MetadataAlerts/TriggerTypes/Date.php
* Previously date alerts would trigger at both the start and the end
date of a date range.
* This change retains that as a default but also makes it possible to
specify whether the alert gets triggered on the start or the end of the
date range
=> Add date_part setting for date metadata alerts

app/lib/MetadataAlerts/TriggerTypes/Modification.php
* Previously _if_:
* you have an element inside a container and
* the container is multi valued
* _then_ filtered alerts do not get triggered.
* This change compares the individual values for an attribute rather
than concatenated values.
=> Trigger metadata alert filters for multi value containers

app/lib/Plugins/SearchEngine/BaseSearchPlugin.php, app/lib/Plugins/SearchEngine/SqlSearch2.php
PR addresses SqlSearch2 issue where field-level searches on fields using modified indexing ('INDEX_AS_IDNO', 'INDEX_ANCESTORS', 'CHILDREN_INHERIT', 'ANCESTORS_INHERIT', 'INDEX_AS_MIMETYPE') would not manifest indexing effects due to SqlSearch2 performing queries directly on the underlying data.
SqlSearch2 will now use the index when these modifiers are present in search_indexing.conf
=> Fix SqlSearch2 issue where field-level searches on fields using modified indexing

composer.json
PR bumps version of flysystem library include due to reported security vulnerability.
=> Bump library version

app/lib/HistoryTrackingCurrentValueTrait.php
* It's already possible to limit the relationship types that can be
created using a policy. _If_ relationships exist with other
relationship types these still get rendered.
* This change prevents inapplicable relationship types from being
rendered
=> Respect restrictToRelationshipTypes setting for getHistory rendering

app/lib/ModelSettings.php
PR changes type list control in configuration settings forms to use hierarchical rendering rather than a flattened list. This more accurately reflects the configured schema and prevents issues when two types in different locations of the hierarchy have the same name.
=> Make type list menu in settings use hierarchical rendering

app/lib/Utils/CLIUtils/Media.php
PR adds option to caUtils reprocess-media to skip specified mimetypes.
=> Add option to skip mimetypes in media reprocessing

app/models/ca_bundle_displays.php
PR adds display option for text elements to control how line breaks are rendered. Two modes are now supported: "display as HTML" which returns text as-is (default) and "preserve breaks", which converts newlines to HTML breaks.
=> Add display option for text metadata elements to convert text line breaks

app/lib/BaseEditorController.php, app/lib/BaseObject.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/Error/errors.en_us, app/models/ca_storage_locations.php, assets/ca/ca.genericbundle.js, assets/ca/ca.relationbundle.js, themes/default/views/bundles/ca_attributes.php, themes/default/views/bundles/hierarchy_location.php, themes/default/views/bundles/history_tracking_chronology.php, themes/default/views/editor/movements/quickadd_html.php
PR includes various fixes and improvements to movement-based location tracking, including:
1. Automatic restriction of movement-record based storage location relationship bundle to policy-configured type (previously it would show all types available in the editor, which would often result in movements without appropriately linked locations).
2. Reworked error checking for storage location move-specific movement form.
=> Impovements to movement-based location tracking

app/helpers/errorHelpers.php, app/lib/Configuration.php, app/lib/ConfigurationExporter.php, app/lib/ModelSettings.php, app/lib/Search/SearchResult.php, app/models/ca_site_pages.php
PR provides miscellaneous fixes, including:
1. Fix typos in comments
2. Don't set list default in item type settings UI element
3. Honor _default paths in site pages
4. Increase searchResult cache size
5. Ensure restrictToTypes settings in exported profiles use codes, not numeric ids
6. Properly check array params on exception screen
=> Miscellaneous fixes

app/lib/Plugins/SearchEngine/SqlSearch2.php
PR resolves debugging warning when attempting to use idno equivalent to search on numeric intrinsics such as type_id.
=> Resolves #1039 - Don't try to cast list-based numeric intrinsics

assets/ca/ca.idnochecker.js
PR addresses issue where multipart idnos with a drop-down component are rendered incorrectly for newly created records, with the drop-down having no selectable options.
=> Live update of multipart idnos broken for newly created records when policy includes a dropdown

app/conf/oai_provider.conf, app/helpers/accessHelpers.php, app/lib/Browse/BrowseEngine.php, app/lib/Search/SearchEngine.php, app/lib/Service/OAIPMHService.php, app/models/ca_data_exporters.php
PR adds restrictToTypes and excludeTypes option to OAI provider, allowing restriction of results to specific record types, as requested in GitHub issue #1024. Also resolves issue where provider could experience fatal error due to incorrect seeking through returned result set.
=> Improvements to OAI provder service

app/models/ca_bundle_displays.php
PR prevents fatal error when a list metadata element without a valid list configured is used in a display.
=> Prevent fatal error in display due to misconfiguration

assets/ca/ca.querytranslator.js
PR resolves issue where queries in builder using "-" (such as date ranges or negative numbers) would cause errors when inequality operators were used (less than, less than or equal, greater than, greater than or equal)
=> Resolves #1050 by quoting queries with "-" in them

app/lib/Plugins/Media/PDFWand.php
PR resolves issue where presence of compressed derivative PDF file could cause save of PDFs into media metadata elements to fail.
=> Save compressed files

app/lib/Parsers/TimeExpressionParser.php
PR prevents warnings to screen when invalid UTF-8 is passed to the parser.
=> Catch failure to tokenize (typically due to invalid UTF-8 input)

app/models/ca_users.php
PR ensures cached value for getUserRoles() respects passed value of "skipVars" option.
=> Make sure caching takes into account "skipVars" option setting

app/lib/Parsers/TimeExpressionParser.php, tests/lib/Parsers/TimeExpressionParserTest.php, tests/models/historyTrackingCurrentValueTest.php
PR resolves issue with date parser where dates ranges using the dash separator with no spaces between dates and separator would fail.
=> Fix ranges with no spaces around dash separator

app/helpers/searchHelpers.php, app/lib/Parsers/TimeExpressionParser/en_AU.lang, app/lib/Parsers/TimeExpressionParser/en_CA.lang, app/lib/Parsers/TimeExpressionParser/en_GB.lang, app/lib/Plugins/SearchEngine/SqlSearch2.php, app/lib/Search/Common/Parsers/LuceneSyntaxLexer.php, app/lib/Search/Common/Parsers/LuceneSyntaxParserContext.php, app/lib/Search/Common/Parsers/QueryEntry/PhraseQueryEntry.php, assets/ca/ca.querytranslator.js, tests/models/historyTrackingCurrentValueTest.php
PR addresses issues with query builder user interface:
1.  "contains" queries on phrases fail
2.   BCE date queries fail when using en_AU, en_GB and en_CA locales
3.   Some container elements may be omitted from query builder field list
=> Fix various query builder UI errors

app/conf/translations.conf, app/helpers/utilityHelpers.php
PR extends translation.conf "strings" replacement feature to support locale-specific replacements. Previously, string replacements would apply to all locales.
=> Add support for locale-specific replacements in translation.conf "strings" feature

app/lib/BaseEditorController.php, app/lib/BaseSettings.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/HistoryTrackingCurrentValueTrait.php, app/lib/ModelSettings.php, app/lib/Search/SearchBase.php, app/models/ca_editor_ui_screens.php
PR reimplements "currentValuesOnly" option for BundlableLabelableBaseModelWithAttributes::getRelatedItems():
1.  Now uses history tracking current value policies in place of old (basically useless) heuristics
2. Updates editor relationships bundles to honor policies
3. Updates batch editing off of relationship bundles to honor current value policies
=> Rework bundle-level "currentValuesOnly" option to honor history tracking policies

app/helpers/post-setup.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/models/ca_acl.php
PR declares ACL constants in post-setup.php to ensure they are set prior to parsing of config files. In Pawtucket where ACL may be set by default value, when these constants are not set most data will fail to display. In Providence ACL should be set with user's specific privs, so initialization is not so critical, but we make the change here just in case and for consistency with the Pawtucket code base.
=> Declare ACL constants in post-setup.php 

app/lib/Parsers/DisplayTemplateParser.php
PR addresss issue where display template parser will fail to emit content if template has only nested units with no top-level content.
=> Address issue where display template parser will fail to emit content

app/controllers/find/RelatedListController.php
* Previously relationships to other records in the same table would
always display using the 'forward' sense.
* Adapts logic used elsewhere in CA.
Fixes #1062
=> #1062 Make it possible to have bidirectional self rels in related lists

app/lib/Parsers/TimeExpressionParser/fr_CA.lang
PR fixes typo in Canadian French date/time parser locale file that would cause June date expressions to fail.
=> Fix typo in translation file

app/helpers/mediaPluginHelpers.php
* Current version of PDFminder returns exit code of 0.
=> Detect PDFminer path using the --version flag

app/conf/app.conf, app/helpers/displayHelpers.php, app/lib/Error/errors.en_us, app/lib/Exceptions/MediaExistsException.php, app/lib/RepresentableBaseModel.php, app/models/ca_object_representations.php
PR adds functionality to prevent duplicate representations from being uploaded. When a dupe upload is attempted it will be rejected with an error message pointing the user to the existing media. 
Also added app.conf directive to control whether duplicate uploads are allowed and sets default behavior to not allow duplicates. This is a change from previous behavior, where dupes were allowed.
=> Add functionality to prevent duplicate representations from being uploaded

app/helpers/displayHelpers.php, app/lib/Utils/CLIUtils/Media.php
PR addes CLI Utils command to detect duplicate media representations. Current implementation cannot check attribute media for duplicates. This will be added in the near future.
=> Add CLIUtils option to detect duplicate media

app/lib/Plugins/Media/Mesh.php
PR limits GLTF file parsing to files <= 1mb to avoid performance issues and memory exhaustion.
=> Don't try to read GLTF files > 1mb

app/lib/Browse/BrowseEngine.php
PR disables attribute caching in browse due to unexpected side effects in certain situations leading to incorrect text output.
=> Caching here can have unexpected side-effects

app/helpers/post-setup.php, app/lib/BaseModel.php, app/lib/Search/SearchIndexer.php
PR adjusts PHP decimal precision to avoid truncation of historic date/time format (which is a large floating point number). When truncation occurs it typically manifests as loss of "circa" specification in inexact dates.
=> Circa dates lose "circa" specification due to Insufficient decimal precision

app/models/ca_data_exporter_items.php, app/models/ca_data_exporters.php, setup.php-dist
PR adds new exporter options for rewriting of output using regular expressions and simplified skipping of blank values export values. The new "skipIfEmpty" option skips an export mapping if the source value is blank. Previously skipping required use of "omitIfEmpty", which requires specification of the value to test for blank-ness. "skipIfEmpty" assumes the current source, and is more convenient for this very common case.
Also fix minor issue where long exporter codes could cause failure when attempting to output an existing exporter to an XLSX file.
=> Add new exporter options

app/lib/BatchProcessor.php
PR sorts files in media importer prior to import, to ensure predictable order. Previously, unsorted output of scandir() was used.  Potential fix for https://github.com/collectiveaccess/providence/issues/1069
=> Sort by filename before processing. May resolve #1069.

app/lib/BaseEditorController.php
* Fixes warning about not being able to set the type_id if that has
already been set for a record.
=> Only set context for idno if it isn't already set.

app/helpers/errorHelpers.php, index.php, themes/default/views/system/configuration_error_html.php, themes/default/views/system/error_html.php, themes/default/views/system/fatal_error_html.php, themes/default/views/system/no_setup_html.php
PR adds alert when no setup.php file is present (vs. previous behavior of splurting a PHP error on screen), and adds a situation-specific error (rather than raw MySQL error text) when database login fails.
=> Add setup error messages 

app/models/ca_bundle_displays.php
PR addresses issue where templates in generic bundles in a display will not render reliably due to "generic" bundle specifier being incorrectly used as relative-to-container value.
=> Fix issue where templates in generic bundles in a display will not render

app/plugins/prepopulate/prepopulatePlugin.php
We're currently using prepopulate with an `edit` configuration which is resulting in change log entries for records every time you view them rather than when you actually edit them. 
I think this change will only save the record if there have been any actual changes as a result of the prepopulate.
=> Only save record on prepopulate if there have been any changes.

app/lib/RepresentableBaseModel.php, app/models/ca_data_importers.php
PR resolves is_primary order issue reported in #1069 by changing is_primary value on import to "passive" mode. (Eg. first imported is primary).
=> Resolve #1069 by setting is_primary passively

app/lib/Plugins/InformationService/AAT.php
A simple addition to allow admins to select to order the results by the term or leave it in the default order.
=> Option to order AAT results by term

app/lib/Attributes/Values/LCSHAttributeValue.php
PR removes LCSH dependency on Zend_Feed lib when performing text-only LCSH lookups. Zend_Feed is no longer maintained in the maintenance port of ZendFramework 1.x
=> Remove LCSH dependency on Zend_Feed lib 

app/lib/BaseModelWithAttributes.php
Bundle codes were showing incorrectly for fields outside of containers and for containers within containers.
This fixes both of these issues by not showing the bundle code on non-container fields (the bundle header will cover these) and by gathering any containers within containers during the loop and adding them to $container_bundle_code.  
I have only tested the container_bundle_code on 2 deep containers, will need testing with more nested containers.
=> Tweaked bundle code display

app/conf/app.conf, app/controllers/find/QuickSearchController.php
PR forces filtering of quicksearch input for XSS and changes overall form filtering default to active. Filtering had been disabled by default (opt-in) for performance reasons and due to user complaints:
-  For virtually all installations, user input is trusted and unfiltered input is preferred – some users do mean to enter literal markup. 
- Filtering impact on performance is negligible in normal use but can become an issue in large data imports.
With this change in default configuration, filtering is now opt-out.
=> Filter quicksearch terms and form input

app/lib/BaseFindController.php
PR changes file extensions for csv and tab-delimited exports to .csv and tsv respectively.
=> Change file extensions for delimited exports

app/lib/Controller/Request/RequestHTTP.php
PR pulls port off of hostname to better handle cases where non-standard ports are being used.
=> Modify background indexing to better handle non-standard ports

app/conf/app.conf, app/controllers/find/QuickSearchController.php, app/lib/BaseModel.php
PR adds filtering to remove external references in HTML input (Eg. <img> tags) . This prevents a situation where arbitrary urls are fetched on the server side when generating PDFs. (Thanks to @haxatron for pointing this out). Also filter HTML tags from quicksearch, to prevent reflection of html content in results message (and because we don't want to be including html tags in quicksearch, which is not supported). (Thanks to @0xamal for pointing this out).
=> Add filtering to remove external references in HTML 

app/helpers/errorHelpers.php
PR adds filtering of external references to stacktrace display, to avoid broken markup and potential XSS.
=> Filter params in stacktrace

app/helpers/post-setup.php, app/lib/ConfigurationCheck.php
PR modified bootstrap process to use context document root where available in order to support path detection when Apache aliases are configured.
=> Use context document root where available

app/lib/Search/SearchIndexer.php
PR checks for case where somehow there's more than one preferred label on a row. When hierarchical indexing is enabled this state (which shouldn't happen, although if you're messing with the database directly it could) will cause indexing to barf when  multiple ids are returned in a single indexing row. This patch just ignores anything after  the first returned label. This seems reasonable in this situation, which shouldn't actually happen and generally does not happen. (There is only a single report of this happening in the "real world").
=> Check for case where somehow there's more than one preferred label

app/lib/BundlableLabelableBaseModelWithAttributes.php
PR forces primary table to be skipped if it is incorrectly included in the list of additional tables to compare against. This prevents odd behaviors than can prevent creation of new records.
=> Skip primary table when evaluating cross-table idno uniqueness

assets/ca/ca.checklistbundle.js
PR fixes incorrect rendering of multivalue checklists when underlying list has default value. In this case the default is shown as checked whether or not it's actually applied to the record.  This is due to defaults being set explicitly in HTML markup, whereas current values are set via jQuery. The change wipes any pre-checked (list default) checkboxes when setting current values in the checklist.
=> Fix rendering of multivalue checklists where underlying list has default value

app/conf/app.conf, app/conf/media_processing.conf, app/lib/BaseModel.php, app/lib/BundlableLabelableBaseModelWithAttributes.php, app/lib/RepresentableBaseModel.php, app/models/ca_data_importers.php, app/models/ca_object_representations.php
Normally all configured versions are generated when media is uploaded. In some cases it  may be desirable to not create a version if a file exceeds a certain size. For example, it  may not be practical to store large original, high-quality media files, but the derivatives of that file are still required. In this case you can specify in the media_processing.conf configuration file  that selected versions be skipped after a threshold is reached, and optionally that another, existing, version  is used in its place whenever it is referenced. The SKIP_WHEN_FILE_LARGER_THAN and REPLACE_WITH_VERSION  options may be set for this purpose.
PR implements options for situations where skipping versions must be dependent upon metadata in the representation record, rather than just file type and size. …
=> Add configurable media version skipping options

app/lib/Parsers/TilepicParser.php
PR strips EXIF orientation tag from tilepic tiles, resolving incorrect display for images with orientation set.
=> Strip EXIF orientation tag before generating tilepic tiles for gmagick.

app/lib/Controller/Request/RequestHTTP.php
PR addresses issues for systems running PHP-FPM proxies where quick search expressions containing spaces (or other URL escaped characters) will throw an invalid controller error when "full results" is selected. This is due to a bug in PHP processing of content for $_SERVER['SCRIPT_NAME'] in several PHP 7.x versions when running as PHP-FPM. See https://bugs.php.net/bug.php?id=74129.
=> Prevent invalid controller path errors for quick searches that include spaces

app/lib/BaseSearchBuilderController.php, app/lib/BaseSearchController.php
PR remove behavior to default to set order in searches on sets, as this seems to confuse 8 out of 10 users.
=> Remove default to set order in searches on sets

app/lib/ConfigurationExporter.php, install/inc/schema_mysql.sql
PR addresses two issues with recently added metadata element soft delete behavior:
- Set schema default for delete flag to 0 (not deleted)
- Filter deleted elements when exporting configuration profile
=> Resolve issues with metadata element soft delete behavior

app/models/ca_data_exporters.php
PR implements exporter behavior to convert delimited string value to repeating values when repeating tag option and delimiter option are both set.
=> New exporter behavior to support creation of repeating export values from delimited string value

app/models/ca_list_items.php
PR rewrites find criteria for list items to avoid errors with certain types of criteria, and makes list items enabled by default.
=> Rewrite find criteria for list items to avoid errors

app/helpers/utilityHelpers.php, app/lib/Utils/CLIUtils/Maintenance.php, app/lib/Utils/DataMigrationUtils.php, app/models/ca_entity_labels.php
PR modifies processing and sortable name generation:
1.  Treat parentheticals as suffixes when following surname
2. Pass organization names through standard sortable value processing to ensure stripping of articles.
3. Strip repeating spaces from sortable values, which can undesirably skew sort order
4. Add option to caUtils to limit rebuilding of sort values to specific tables.
=> Improve processing and sortable value generation for organization entity names

app/controllers/administrate/maintenance/ExportConfigurationController.php, app/lib/ConfigurationExporter.php
PR modifies profile exporter to prevent truncation of long (> 30 chars) identifiers, and provides exported profiles with more relevant <profileName> values.
=> Profile exporter improvements

app/lib/Import/DataReaders/MARCDataReader.php
Hi CA team,
This PR is to allow such situations :
```
701  | $3 11899819 $o ISNI000000012132618X $a Désert $b Gabriel $f 1924-2004 $4 070
701  | $3 11925318 $o ISNI0000000034278298 $a Specklin $b Robert $f 1916-2008 $4 070
```
Actually, only one value was kept. This mod allows to keep both and access individual values through ^701/a0 and ^701/a1 for authors last names, without breaking former syntax, and keeping backward compatibility with mappings.
=> MARCDataReader : handling repeated fields

app/helpers/utilityHelpers.php
Hi CA Team,
Adding the "/" to the not-to-be-removed parts of a template, as "^701/a" is a valid template, handled by method get inside MarcDataReader 
```
public function get($ps_spec, $pa_options=null) {
// [...]
list($ps_code, $ps_subcode, $ps_indicators) = explode('/', $ps_spec);
```
I know these times marc tends to be more and more replaced by XMLmarc, but there are still some uses for example with Z9350 when SUTRS is not available.
Gautier
=> caExtractTagsFromTemplate : broken for marc

app/lib/BundlableLabelableBaseModelWithAttributes.php
Hi,
Following the docs (https://manual.collectiveaccess.org/configuration/mainConfiguration/multipart_id_numbering.html) the separtor is mandatory, but should be allow to be empty.
Most (if not all) Numbering will have a fallback value for unset values so I assume this BaseModel forcing the dash/minus for emtpy values is no longer valid logic ?
I flaws our (valid) Multipart ID definition of constant (B) with serial (000001) with empty separator from wanted B000001 to unwanted B-00001
=> allow empty separator in ID numbering

app/plugins/prepopulate/prepopulatePlugin.php
When the target array is empty, going inside merge mode will lead to errors due to the fact that it tries to use getValues() from an empty array. Now will fall back to overwrite mode if the target array is empty
=> Small bug-fix for prepopulate

assets/ca/ca.hierbrowser.js
Hi,
The code was already modified before but can't the extra testing for level 0 be dropped altogether. It doesn't seem user-friendly/intuitive to have the arrow navigation for children when there are no child items to be expected (the first test). 
You still can select the item, and there doesn't seem to be other functionality to the childless button (other than clearing the (previous) next level) - or I may have missed that feature :p
=> remove child navigation button in hierarchy browser for childless listitems

app/plugins/prepopulate/lib/applyPrepopulateRulesTool.php, app/plugins/prepopulate/prepopulatePlugin.php
There was a missing parameter in app/plugins/prepopulate/lib/applyPrepopulateRulesTool.php that made the two rules broken. Meanwhile I fixed a typo in option's description
=> Bug-Fix: Prepopulate restrictToRules and excludeRules not working

app/lib/Attributes/Values/WeightAttributeValue.php
there is some cleaning done in Weight attribute for trailing zero's but that takes point as decimal separator hard coded, while some locales have comma as the decimal separator and that can give unwanted results.
For instance 1.160 is "cleaned" to 1.16 where is should stay as-is (1160,00 or 1.160 without decimals)
The registered value is always correct in the db (value_decimal), it's just this presentation that can be a bit off for some values (1.161 stays 1.161 because it doesn't go through the cleaning)
=> account for decimal separator while trailing zero cleaning

app/conf/search_query_builder.conf, app/helpers/searchHelpers.php, app/lib/Plugins/SearchEngine/SqlSearch2.php, assets/ca/ca.querytranslator.js
In older versions of Providence it was possible to perform searches such as `_fulltext:foobar` via the API or as a part of search query syntax and in the search query builder.
This restores that ability.
=> Fix search query builder fulltext search

themes/default/views/bundles/history_tracking_chronology.php
* Previously this was expecting a $vn_type_id to be defined for movements but this is not done in a similar manner to ca_occurrences, ca_collections and ca_entities which loop over occurrence types
* Reading the code I see that loans are also not broken out by types so fixing the resulting JS error there as well
=> Fix always_create_new_movement/always_create_new_loan quickadds

themes/default/views/bundles/history_tracking_chronology.php
* Previously a quick add would create two inputs with the related movement/loan/occurrence
Before: 
After:
=> Only add a single related item when always quick adding in history tracking

app/models/ca_bundle_displays.php
boolean use item values only defined and set in one if condition, used twice later but possibly without existing. Might as well define as default false then?
=> define and set boolean use item values

app/plugins/relationshipGenerator/relationshipGeneratorPlugin.php
Hi,
We got this Uncaught TypeError: Cannot access offset of type string on string on the relationshipGenerator plugin
$va_trigger[$key], looks indeed that the current trigger (looped from $va_triggers) is already a string, and cannot be read with index key, so without knowing all context keeping the original $va_triggers seems the only choice here ? (makes you wonder how forgiving php<8 was if that wasn't a problem earlier - dates 2014)
So not completely sure this will "solve" the problem, but it clears the obvious typeError.
Peter
=> fix Uncaught TypeError: Cannot access offset of type string on string

app/lib/Controller/Request/RequestHTTP.php
during cli actions like rebuilding search index via caUtils, a lot of warnings are generated because $_SERVER['REMOTE_ADDR'] is not defined. Maybe localhost can be returned for that final return in that circumstance.
=> fix remote address (ip) for cli utils

app/lib/Utils/CLIUtils/Maintenance.php
Several of the messages produced by fix-permissions are confusing, updating the change paths to improve accuracy.
=> Adjustments to fixing permissions messages

app/lib/Plugins/InformationService/Iconclass.php
The iconclass service old API endpoint seems to redirect to an html landingpage now, ie.:
http://iconclass.org/rkd/9/?q=europa&q_s=1&fmt=json
and no longer to a json with records/results.
I tried to stay as close to the original implementation with the (new?) documented API's https://iconclass.org/docs
What appeared to have worked in the past in one request, is now to be done in subsequent requests, the first (language based) search to get results with key, the next to get the (language based) labels for the resulting keys/ids.
https://iconclass.org/api/search?q=europa&lang=en&size=999&page=1&sort=rank&keys=0
[
https://iconclass.org/92B1218.json,
..
]
It works on both php7 as php8 installations.
PS
I've kept the implementation simple, but I would like to propose a variation in a later …
=> update iconclass API lookup

app/lib/Plugins/InformationService/Iconclass.php
some terms didn't go well,
iconclass has + sign reserved, and spaces are translated into + with regular urlencode, rawurlencode instead does %20
=> rawurlencode for reserved + signs

app/lib/MetadataAlerts/TriggerTypes/Modification.php
* Prior to this the attributeDidChange call was only called if there was a matching filter. If the alert didn't have a filter (only list elements have a filter) then this was being ignored.
* Now only disable checking for changes if the element was being filtered and the value of the element wasn't one of the filter values.
=> NOJIRA Make non-filtered metadata alerts trigger

app/lib/HistoryTrackingCurrentValueTrait.php
* Default to current behaviour which renders a delimited list of preferred labels
* Requires config in app.conf:
```
history_tracking_policies = {
defaults = {
ca_objects = current_location
},
policies = {
current_location = {
name = _(Location),
table = ca_objects,
contents = {
delimiter = ,
expandHierarchically = 1,
template = "^ca_object_representations.media.icon ^ca_objects.preferred_labels"
},
elements = {
ca_movements = {
__default__ = {
date = ca_movements.removal_date,
setInterstitialElementsOnAdd = [],
template = "
<unit relativeTo='ca_movements'>^ca_movements.removal_date</td> ^ca_storage_locations.hierarchy.preferred_labels.name%maxLevelsFromBottom=6&delimiter=_➜_</unit>",
trackingRelationshipType = part,
useRelated = ca_storage_locations,
useRelatedRelationshipType = part,
} …
```
=> NOJIRA Add support for template for contents display in history tracking policy

app/lib/Controller/Request/Session.php
was playing with GraphQL and got "\"kid\" empty, unable to lookup correct key" from the Firebase php-jwt, where getKey expects a jwt Key or an array of Keys with kid; but it currently got a string, not a key. Apparently the signature got changed where decode gets the Key directly.
PS: documentation wasn't clear (or no longer valid) where the jwt token should go, I think I used to pass it as a query parameter but now it has to be passed as an argument in the body. Maybe it got there automagically in earlier php7 ?
Passing via Authorization Bearer {token} Header still works.
`{"query":"query {get(jwt:\"eyJ0eXA..., table:'ca_objects', identifier:...`
=> update key setting for jwt decode

themes/default/views/bundles/ca_entity_labels_nonpreferred.php
The Display Name for the non-preferred label in entity (for IND_SM) was inconsistent with the width for the preferred label. This brings them both to the same width.
=> Width of display name

app/lib/BaseFindController.php, app/lib/Plugins/TaskQueueHandlers/batchEditor.php, app/models/ca_bundle_displays.php
Fixing undefined array warning for taskqueue batch editor and search
=> PHP8 Compatibility

index.php
Hi CA team & Seth,
This PR adds the ability to register a CDN for plugins inside Providence, I'll do the same feat inside Paw in the next days/weeks. The intend is to allow a plugin to register its own CDNS, I usually use wavesurfer-js to display audio waveforms in audio related projects (https://wavesurfer-js.org/) that uses cdnjs.cloudflare.com as CDN, or D3, datatables...
=> NOJIRA : hookAddDomainSecurityPolicy allowing plugins to register CDNs

app/lib/RepresentableBaseModel.php
Hi,
We noticed a bug when using the media quick add (manually upload single media file from local source) where idno's where created blank, thus resulting in the duplicate idno warning, even when using multipart ids. On the short-term we could solve this by allowing duplicate idno's but the better option would be to have curated idno's as intended.
It appears the quick add form does not use the idno form element (like at other places with next idno suggestion), however it does gets added to the $pa_values['idno'] anyway through request getParameter (without form presence shouldn't be ??)
The idno multiparting is handled properly in $t_rep->setIdnoWithTemplate, but gets blanked out again by $t_rep->set('idno'). Without knowing with certainty all scenarios that could lead here (import, bulk …
=> check for generated idno

install/profiles/xml/base.xml
Because the typename refers here to the entity, not to the loan, the correct expression is "borrowed by".  What we want is [loan] is borrowed by [borrower].  The existing phrase was wrong: [loan] is borrowed from [borrower].
Fixes #1426
=> "borrowed from" should be "borrowed by"

app/models/ca_data_importers.php
Update ca_data_importers to add mapping option to skip on no idno - Fix missing if.
Previous commit has a closing brace without the matching opening tag and if statement. Apologies.
=> Fix invalid syntax in ca_data_importers

app/lib/BaseRelationshipModel.php, app/lib/BatchProcessor.php, themes/default/views/bundles/related_list.php
=> Dev/php8 - PHP8 Fixes

app/conf/app.conf, app/lib/Controller/Request/RequestHTTP.php
* Does not disable the queue, just the requests that happen at the very end of _every_ _single_ _page_ _call_.
=> Make it possible to disable async search indexing requests.

install/profiles/xml/dacs_heritage.xml
Fixes #1508
Removes duplicate relationship types so that they are not displayed twice in the select list.
=> Removed duplicate relationship types from dacs_heritage.xml

app/lib/BaseEditorController.php
Hi @collectiveaccess,
I found a bug when trying to configure the file name in a summary print template.
It seems like the value was not properly assigned to $this->view->getVar('filename') when it exists.
=> Fixed bug with filenaming for summary print templates

app/controllers/logs/GlobalChangeController.php
@collectiveaccess
Same bug fix as in https://github.com/collectiveaccess/providence/pull/1547
since this bug is also present in CA 2.0
=> Bug Fix CA 2.0: "all changes" not displayed in change log

app/controllers/logs/GlobalChangeController.php
When selecting the option "all changes" in the change log there is no difference with the option "adds": only insertion changes are displayed and other changes are filtered out. This is due to a variable transmitted as an empty string instead of the expected null value.
=> Bug Fix: "all changes" not displayed in change log

app/controllers/logs/GlobalChangeController.php
Hi @collectiveaccess,
I would like to suggest here a small improvement which would be very helpful to us and maybe to others too.
This allows to display changes to relationship tables in the global change log when no specific table is selected.
Same as https://github.com/collectiveaccess/providence/pull/1554 but in CA 2.0
=> Display changes to relationship tables in Global Change Log (2.0)

app/controllers/logs/GlobalChangeController.php
Hi @collectiveaccess,
I would like to suggest here a small improvement which would be very helpful to us and maybe to others too.
This allows to display changes to relationship tables in the global change log when no specific table is selected.
=> Display changes to relationship tables in Global Change Log (1.8rc5)

app/helpers/displayHelpers.php, themes/default/views/bundles/download_file_binary.php
This small change is to allow file names for object representations to support parentheses, since they are allowed special characters on any file system.
This is something we would like to have, and it might be beneficial for others as well.
=> Allow parentheses in object representation file names (dev/php8)

assets/ca/ca.labelbundle.js
Bug fix for ca.labelbundle.js:
I removed the extra parenthesis which causes a SyntaxError and I converted the variable passed as an argument to a callback function to avoid a TypeError.
=> Fix SyntaxError & TypeError in ca.labelbundle.js

assets/ca/ca.labelbundle.js
Fixed a bug with the locale of non preferred labels caused by a wrong interpretation of the result of findIndex(). findIndex() returns -1 when no index is found.
=> Fixed Bug with locale of non preferred labels

install/inc/page1.php
The existing link redirects to the documentation main index
=> Correct the installer link to documentation about profiles

composer.json
This API package has a transitive dependency on php-http/message-factory which is considered abandoned.
This change upgrades github-api to the first version which depends on php-cache-plugin v2 and allows the message-factory dependency to be changed.
=> Upgrade github-api dependency

app/lib/Auth/Adapters/Shibboleth.php
When installed via composer (the recommended method), simplesamlphp will be placed under CA's vendor directory.  Installing under /var/simplesamlphp is only suggested by upstream for source installs.
Because of that this PR moves the include path used by CA away from /var/simplesamlphp in to CA's vendor location.
Closes #1573.
=> Update simplesaml load path

composer.json
The current graphql-client and stash depended on the old version of psr/cache while simplesamlphp depends on newer versions of psr/cache. To resolve that conflict grapql-client and stash are being upgraded to a newer version which supports at least psr/cache v2.0
For stash, this makes its minimum supported PHP version 8.
SimpleSAMLphp version 2.0 will end its security support later this year, so newer versions should be used where possible. To aid in identifying simplesamlphp for future users it has been added to the suggests section in composer.
=> Add simplesamlphp and update dependencies

app/conf/authentication.conf
Having a comma after shibboleth_users_default_roles = [cataloguer] meant CA configuration had an entry for shibboleth_users_default_groups prefixed by a comma.
`',shibboleth_users_default_groups' => array ( 0 => 'cataloguer', )`
Removing the comma shibboleth_users_default_groups is named correctly and can be overridden locally.
This change is unlikely to have a behavioural change but hasn't been tested.
=> Remove incorectly parsed comma

app/helpers/mailHelpers.php
I would like to suggest supporting UTF-8 encoding in PHPMailer, which solves issues with non-latin characters not being
displayed properly in the mail's content.
=> UTF-8 Encoding for PHPMailer

app/lib/MetaTagManager.php
This adds the addScript function to the MetaTagHandler, with rendering of the script in <meta>.
This would allow to inject (js) scripts specific for plugins (example: /app/plugins/myCustomPlugin/assets/js/my_custom_script.js), and would allow easier handling (ie. via enabling/disabling plugin and not by tampering /conf/local/assets.conf)
it follows the other meta elements (like stylesheet links)
MetaTagManager::addScript(__CA_URL_ROOT__."/app/plugins/myCustomPlugin/assets/js/my_custom_script.js",'text/javascript');
=> add addScript to MetaTagHandler

app/lib/Service/IIIFService.php
Fixes #1605
Arbitrary value of 1 hour allows web browsers to close and re-open overlay viewers without requesting image tiles every time. This patch will need to be copied to Pawtucket as well.
=> Enabled client-side caching in the IIIF service.

.htaccess
Fixes #1621
Changes to `.htaccess` were needed to permit `assets/pdfjs/viewer/locale` file retrieval.
=> Allow retrieval of any .properties file

app/conf/app.conf, app/helpers/utilityHelpers.php, app/lib/ConfigurationCheck.php, app/tmp/purifier/.htaccess
This removes the only writeable path under vendor/, allowing the full directory path to be marked read only
To enable the change a new subdirectory is created in tmp to hold serialisers working data.
=> Make HTMLPurifier path configurable

app/lib/BatchProcessor.php
hookSaveItem is fired after a Save event in the interface, allowing to prepopulate metadatas for example. If you batch process records on those metadatas, the subsequent computes are not executed.
This PR aims to fire hookSaveItem after a batch treatment.
=> NOJIRA BatchProcessor : handles hookSaveItem after a batch processing

app/lib/Search/SearchIndexer.php
"TRUNCATING ca_objects" is not something most people want to while trying to tweak an install...
CAVEAT: this is not an obscure message, and existing translations will miss it, pick your poison.
=> Fix needlessly alarming "TRUNCATING" message

app/service/controllers/ItemController.php
Following on this PR #1716 -- the `checkAccess` param was still not working as expected.
It turns out I didn't quite understand how closures in PHP work - I needed to call use($check_access) so that the closure could access the variable from the parent context.
It's working correctly now.
=> provide $check_access to the array_map closure with use

app/lib/Utils/CLIUtils/Maintenance.php
Two updates to htmlpurifier related behaviours.
- The first ensures the htmlpurifier directory created during `clear-caches` is writable by the owner of the temp directory. 
- The second updates `fix-permissions` to correct the customisable temp directory path.
=> Purifier path fixes

assets/ca/ca.idnochecker.js
When creating a new ObjectLot (Zugang) and entering an existing inventory number, CollectiveAccess correctly shows the warning “Identifikator wird schon verwendet”.
However, clicking on the generated link did not open the corresponding record, but instead redirected the user to an empty simple search or caused a 404 error.
**Root cause:**
The JavaScript file ca.idnochecker.js built the link by concatenating the raw identifier directly into the search path, for example:
/find/SearchObjectLots/Index/search/FM-2002/356
Because identifiers in many installations include slash characters (/), Apache interpreted these as part of the URL path instead of a search term.
This caused the route not to match and resulted in an empty search page or a “Not Found” error.
**Fix implemented:**
The link …
=> Fix: broken “duplicate identifier” link in IDNo checker (ca.idnochecker.js)
